//////////////////////////////////////////////////////////////////////
// This file was auto-generated by CodeLite's wxCrafter Plugin
// wxCrafter project file: UI.wxcp
// Do not modify this file by hand!
//////////////////////////////////////////////////////////////////////

#include "UI.hpp"

// Declare the bitmap loading function
extern void wxCrafterFiTVkcInitBitmapResources();

namespace {
// return the wxBORDER_SIMPLE that matches the current application theme
[[maybe_unused]]
wxBorder get_border_simple_theme_aware_bit() {
#if wxVERSION_NUMBER >= 3300 && defined(__WXMSW__)
  return wxSystemSettings::GetAppearance().IsDark() ? wxBORDER_SIMPLE
                                                    : wxBORDER_DEFAULT;
#else
  return wxBORDER_DEFAULT;
#endif
} // get_border_simple_theme_aware_bit
bool bBitmapLoaded = false;
} // namespace

SessionBasePage::SessionBasePage(wxWindow *parent, wxWindowID id,
                                 const wxPoint &pos, const wxSize &size,
                                 long style)
    : wxPanel(parent, id, pos, size, style) {
  if (!bBitmapLoaded) {
    // We need to initialise the default bitmap handler
    wxXmlResource::Get()->AddHandler(new wxBitmapXmlHandler);
    wxCrafterFiTVkcInitBitmapResources();
    bBitmapLoaded = true;
  }

  wxBoxSizer *boxSizer1 = new wxBoxSizer(wxVERTICAL);
  this->SetSizer(boxSizer1);

  SetName(wxT("SessionBasePage"));
  SetSize(wxDLG_UNIT(this, wxSize(500, 300)));
  if (GetSizer()) {
    GetSizer()->Fit(this);
  }
}

SessionBasePage::~SessionBasePage() {}

MainViewBase::MainViewBase(wxWindow *parent, wxWindowID id, const wxPoint &pos,
                           const wxSize &size, long style)
    : wxPanel(parent, id, pos, size, style) {
  if (!bBitmapLoaded) {
    // We need to initialise the default bitmap handler
    wxXmlResource::Get()->AddHandler(new wxBitmapXmlHandler);
    wxCrafterFiTVkcInitBitmapResources();
    bBitmapLoaded = true;
  }

  wxBoxSizer *boxSizer4 = new wxBoxSizer(wxVERTICAL);
  this->SetSizer(boxSizer4);

  m_splitterMain = new wxSplitterWindow(
      this, wxID_ANY, wxDefaultPosition, wxDLG_UNIT(this, wxSize(-1, -1)),
      wxSP_LIVE_UPDATE | wxSP_3DSASH | wxBORDER_THEME);
  m_splitterMain->SetSashGravity(0);
  m_splitterMain->SetMinimumPaneSize(250);

  boxSizer4->Add(m_splitterMain, 1, wxEXPAND, WXC_FROM_DIP(5));

  m_splitterPageLeft =
      new wxPanel(m_splitterMain, wxID_ANY, wxDefaultPosition,
                  wxDLG_UNIT(m_splitterMain, wxSize(-1, -1)), wxTAB_TRAVERSAL);

  m_leftPaneMainSizer = new wxBoxSizer(wxVERTICAL);
  m_splitterPageLeft->SetSizer(m_leftPaneMainSizer);

  m_dvListCtrlGroups =
      new wxDataViewListCtrl(m_splitterPageLeft, wxID_ANY, wxDefaultPosition,
                             wxDLG_UNIT(m_splitterPageLeft, wxSize(200, -1)),
                             wxDV_NO_HEADER | wxDV_ROW_LINES | wxDV_SINGLE);

  m_leftPaneMainSizer->Add(m_dvListCtrlGroups, 1, wxEXPAND, WXC_FROM_DIP(5));

  m_dvListCtrlGroups->AppendIconTextColumn(_("Groups"), wxDATAVIEW_CELL_INERT,
                                           WXC_FROM_DIP(-2), wxALIGN_LEFT, 0);
  m_splitterPageRight =
      new wxPanel(m_splitterMain, wxID_ANY, wxDefaultPosition,
                  wxDLG_UNIT(m_splitterMain, wxSize(-1, -1)), wxTAB_TRAVERSAL);
  m_splitterMain->SplitVertically(m_splitterPageLeft, m_splitterPageRight, 0);

  wxBoxSizer *boxSizer12 = new wxBoxSizer(wxVERTICAL);
  m_splitterPageRight->SetSizer(boxSizer12);

  m_sessionsBook =
      new wxSimplebook(m_splitterPageRight, wxID_ANY, wxDefaultPosition,
                       wxDLG_UNIT(m_splitterPageRight, wxSize(-1, -1)), 0);
  m_sessionsBook->SetName(wxT("m_sessionsBook"));
  m_sessionsBook->SetEffect(wxSHOW_EFFECT_NONE);

  boxSizer12->Add(m_sessionsBook, 1, wxEXPAND, WXC_FROM_DIP(5));

  SetName(wxT("MainViewBase"));
  SetSize(wxDLG_UNIT(this, wxSize(-1, -1)));
  if (GetSizer()) {
    GetSizer()->Fit(this);
  }
  // Connect events
  m_dvListCtrlGroups->Bind(wxEVT_COMMAND_DATAVIEW_SELECTION_CHANGED,
                           &MainViewBase::OnSelectionChanged, this);
  m_dvListCtrlGroups->Bind(wxEVT_COMMAND_DATAVIEW_ITEM_CONTEXT_MENU,
                           &MainViewBase::OnContextMenu, this);
}

MainViewBase::~MainViewBase() {
  m_dvListCtrlGroups->Unbind(wxEVT_COMMAND_DATAVIEW_SELECTION_CHANGED,
                             &MainViewBase::OnSelectionChanged, this);
  m_dvListCtrlGroups->Unbind(wxEVT_COMMAND_DATAVIEW_ITEM_CONTEXT_MENU,
                             &MainViewBase::OnContextMenu, this);
}

StartAgentDialogBase::StartAgentDialogBase(wxWindow *parent, wxWindowID id,
                                           const wxString &title,
                                           const wxPoint &pos,
                                           const wxSize &size, long style)
    : wxDialog(parent, id, title, pos, size, style) {
  if (!bBitmapLoaded) {
    // We need to initialise the default bitmap handler
    wxXmlResource::Get()->AddHandler(new wxBitmapXmlHandler);
    wxCrafterFiTVkcInitBitmapResources();
    bBitmapLoaded = true;
  }

  wxBoxSizer *boxSizer16 = new wxBoxSizer(wxVERTICAL);
  this->SetSizer(boxSizer16);

  wxStaticBoxSizer *staticBoxSizer340 = new wxStaticBoxSizer(
      new wxStaticBox(this, wxID_ANY, wxT("")), wxVERTICAL);

  boxSizer16->Add(staticBoxSizer340, 1, wxALL | wxEXPAND, WXC_FROM_DIP(10));

  wxFlexGridSizer *flexGridSizer31 = new wxFlexGridSizer(0, 2, 0, 0);
  flexGridSizer31->SetFlexibleDirection(wxBOTH);
  flexGridSizer31->SetNonFlexibleGrowMode(wxFLEX_GROWMODE_SPECIFIED);
  flexGridSizer31->AddGrowableCol(1);

  staticBoxSizer340->Add(flexGridSizer31, 1, wxALL | wxEXPAND,
                         WXC_FROM_DIP(10));

  m_staticText22 =
      new wxStaticText(this, wxID_ANY, _("Agent:"), wxDefaultPosition,
                       wxDLG_UNIT(this, wxSize(-1, -1)), 0);

  flexGridSizer31->Add(m_staticText22, 0,
                       wxALL | wxALIGN_RIGHT | wxALIGN_CENTER_VERTICAL,
                       WXC_FROM_DIP(5));

  wxArrayString m_choiceClientsArr;
  m_choiceClients =
      new wxChoice(this, wxID_ANY, wxDefaultPosition,
                   wxDLG_UNIT(this, wxSize(250, -1)), m_choiceClientsArr, 0);

  flexGridSizer31->Add(m_choiceClients, 0, wxALL | wxEXPAND, WXC_FROM_DIP(5));

  m_staticTextName =
      new wxStaticText(this, wxID_ANY, _("Session Name:"), wxDefaultPosition,
                       wxDLG_UNIT(this, wxSize(-1, -1)), 0);

  flexGridSizer31->Add(m_staticTextName, 0,
                       wxALL | wxALIGN_RIGHT | wxALIGN_CENTER_VERTICAL,
                       WXC_FROM_DIP(5));

  m_textCtrlName = new wxTextCtrl(this, wxID_ANY, wxT(""), wxDefaultPosition,
                                  wxDLG_UNIT(this, wxSize(300, -1)), 0);
  m_textCtrlName->SetFocus();
#if wxVERSION_NUMBER >= 3000
  m_textCtrlName->SetHint(_("* Enter the session name"));
#endif

  flexGridSizer31->Add(m_textCtrlName, 0, wxALL | wxEXPAND, WXC_FROM_DIP(5));

  flexGridSizer31->Add(0, 0, 1, wxALL, WXC_FROM_DIP(5));

  m_staticTextErrorMessage =
      new wxStaticText(this, wxID_ANY, _("⚠ Session name already exists"),
                       wxDefaultPosition, wxDLG_UNIT(this, wxSize(-1, -1)), 0);
  m_staticTextErrorMessage->SetForegroundColour(wxColour(wxT("rgb(255,0,0)")));
  m_staticTextErrorMessage->Hide();

  flexGridSizer31->Add(m_staticTextErrorMessage, 0, wxALL | wxEXPAND,
                       WXC_FROM_DIP(5));

  m_staticText343 =
      new wxStaticText(this, wxID_ANY, _("Session Group:"), wxDefaultPosition,
                       wxDLG_UNIT(this, wxSize(-1, -1)), 0);

  flexGridSizer31->Add(m_staticText343, 0,
                       wxALL | wxALIGN_RIGHT | wxALIGN_CENTER_VERTICAL,
                       WXC_FROM_DIP(5));

  wxArrayString m_comboBoxGroupArr;
  m_comboBoxGroup =
      new wxComboBox(this, wxID_ANY, wxT(""), wxDefaultPosition,
                     wxDLG_UNIT(this, wxSize(-1, -1)), m_comboBoxGroupArr, 0);
#if wxVERSION_NUMBER >= 3000
  m_comboBoxGroup->SetHint(wxT(""));
#endif

  flexGridSizer31->Add(m_comboBoxGroup, 0, wxALL | wxEXPAND, WXC_FROM_DIP(5));

  m_staticText24 =
      new wxStaticText(this, wxID_ANY, _("Working Directory:"),
                       wxDefaultPosition, wxDLG_UNIT(this, wxSize(-1, -1)), 0);

  flexGridSizer31->Add(m_staticText24, 0,
                       wxALL | wxEXPAND | wxALIGN_RIGHT |
                           wxALIGN_CENTER_VERTICAL,
                       WXC_FROM_DIP(5));

  wxBoxSizer *boxSizer317 = new wxBoxSizer(wxHORIZONTAL);

  flexGridSizer31->Add(boxSizer317, 0, wxALL | wxEXPAND, WXC_FROM_DIP(5));

  wxArrayString m_comboBoxWorkingDirArr;
  m_comboBoxWorkingDir = new wxComboBox(
      this, wxID_ANY, wxT(""), wxDefaultPosition,
      wxDLG_UNIT(this, wxSize(-1, -1)), m_comboBoxWorkingDirArr, 0);
#if wxVERSION_NUMBER >= 3000
  m_comboBoxWorkingDir->SetHint(_("* Choose a working directory"));
#endif

  boxSizer317->Add(m_comboBoxWorkingDir, 1, wxALIGN_CENTER_VERTICAL,
                   WXC_FROM_DIP(5));

  m_buttonBrowseWD = new wxButton(this, wxID_ANY, _("..."), wxDefaultPosition,
                                  wxDLG_UNIT(this, wxSize(-1, -1)), 0);
  m_buttonBrowseWD->SetToolTip(_("Browse for Working Directory"));

  boxSizer317->Add(m_buttonBrowseWD, 0,
                   wxLEFT | wxTOP | wxBOTTOM | wxALIGN_CENTER_VERTICAL,
                   WXC_FROM_DIP(5));

  flexGridSizer31->Add(0, 0, 1, wxALL, WXC_FROM_DIP(5));

  m_checkBoxInnderFolder = new wxCheckBox(
      this, wxID_ANY, _("Create an inner folder within the working directory"),
      wxDefaultPosition, wxDLG_UNIT(this, wxSize(-1, -1)), 0);
  m_checkBoxInnderFolder->SetValue(false);
  m_checkBoxInnderFolder->SetToolTip(
      _("If checked, the working directory is formed by appending the session "
        "name to the specified working directory."));

  flexGridSizer31->Add(m_checkBoxInnderFolder, 0, wxALL, WXC_FROM_DIP(5));

  flexGridSizer31->Add(0, 0, 1, wxALL, WXC_FROM_DIP(5));

  m_checkBoxResume = new wxCheckBox(
      this, wxID_ANY, _("Resume the Latest Session in This Folder"),
      wxDefaultPosition, wxDLG_UNIT(this, wxSize(-1, -1)), 0);
  m_checkBoxResume->SetValue(false);

  flexGridSizer31->Add(m_checkBoxResume, 0, wxALL, WXC_FROM_DIP(5));

  m_stdBtnSizer17 = new wxStdDialogButtonSizer();

  boxSizer16->Add(m_stdBtnSizer17, 0, wxALL | wxALIGN_CENTER_HORIZONTAL,
                  WXC_FROM_DIP(10));

  m_buttonOk = new wxButton(this, wxID_OK, wxT(""), wxDefaultPosition,
                            wxDLG_UNIT(this, wxSize(-1, -1)), 0);
  m_buttonOk->SetDefault();
  m_stdBtnSizer17->AddButton(m_buttonOk);

  m_buttonCancel = new wxButton(this, wxID_CANCEL, wxT(""), wxDefaultPosition,
                                wxDLG_UNIT(this, wxSize(-1, -1)), 0);
  m_stdBtnSizer17->AddButton(m_buttonCancel);
  m_stdBtnSizer17->Realize();

  SetName(wxT("StartAgentDialogBase"));
  SetSize(wxDLG_UNIT(this, wxSize(-1, -1)));
  if (GetSizer()) {
    GetSizer()->Fit(this);
  }
  if (GetParent()) {
    CentreOnParent(wxBOTH);
  } else {
    CentreOnScreen(wxBOTH);
  }
  if (!wxPersistenceManager::Get().Find(this)) {
    wxPersistenceManager::Get().RegisterAndRestore(this);
  } else {
    wxPersistenceManager::Get().Restore(this);
  }
  // Connect events
  m_textCtrlName->Bind(wxEVT_COMMAND_TEXT_UPDATED,
                       &StartAgentDialogBase::OnNameUpdated, this);
  m_buttonBrowseWD->Bind(wxEVT_UPDATE_UI, &StartAgentDialogBase::OnBrowseWdUI,
                         this);
  m_buttonBrowseWD->Bind(wxEVT_COMMAND_BUTTON_CLICKED,
                         &StartAgentDialogBase::OnBrowseWD, this);
  m_checkBoxInnderFolder->Bind(wxEVT_COMMAND_CHECKBOX_CLICKED,
                               &StartAgentDialogBase::OnInnerFolder, this);
  m_buttonOk->Bind(wxEVT_UPDATE_UI, &StartAgentDialogBase::OnOkUI, this);
}

StartAgentDialogBase::~StartAgentDialogBase() {
  m_textCtrlName->Unbind(wxEVT_COMMAND_TEXT_UPDATED,
                         &StartAgentDialogBase::OnNameUpdated, this);
  m_buttonBrowseWD->Unbind(wxEVT_UPDATE_UI, &StartAgentDialogBase::OnBrowseWdUI,
                           this);
  m_buttonBrowseWD->Unbind(wxEVT_COMMAND_BUTTON_CLICKED,
                           &StartAgentDialogBase::OnBrowseWD, this);
  m_checkBoxInnderFolder->Unbind(wxEVT_COMMAND_CHECKBOX_CLICKED,
                                 &StartAgentDialogBase::OnInnerFolder, this);
  m_buttonOk->Unbind(wxEVT_UPDATE_UI, &StartAgentDialogBase::OnOkUI, this);
}

EditFileDlgBase::EditFileDlgBase(wxWindow *parent, wxWindowID id,
                                 const wxString &title, const wxPoint &pos,
                                 const wxSize &size, long style)
    : wxDialog(parent, id, title, pos, size, style) {
  if (!bBitmapLoaded) {
    // We need to initialise the default bitmap handler
    wxXmlResource::Get()->AddHandler(new wxBitmapXmlHandler);
    wxCrafterFiTVkcInitBitmapResources();
    bBitmapLoaded = true;
  }

  wxBoxSizer *boxSizer35 = new wxBoxSizer(wxVERTICAL);
  this->SetSizer(boxSizer35);

  m_toolbar = new wxToolBar(this, wxID_ANY, wxDefaultPosition,
                            wxDLG_UNIT(this, wxSize(-1, -1)), wxTB_FLAT);
  m_toolbar->SetToolBitmapSize(wxSize(16, 16));

  boxSizer35->Add(m_toolbar, 0, wxALL | wxEXPAND, WXC_FROM_DIP(0));

  m_stcEditor = new wxStyledTextCtrl(this, wxID_ANY, wxDefaultPosition,
                                     wxDLG_UNIT(this, wxSize(-1, -1)), 0);
  // Configure the fold margin
  m_stcEditor->SetMarginType(4, wxSTC_MARGIN_SYMBOL);
  m_stcEditor->SetMarginMask(4, wxSTC_MASK_FOLDERS);
  m_stcEditor->SetMarginSensitive(4, true);
  m_stcEditor->SetMarginWidth(4, 0);

  // Configure the tracker margin
  m_stcEditor->SetMarginWidth(1, 0);

  // Configure the symbol margin
  m_stcEditor->SetMarginType(2, wxSTC_MARGIN_SYMBOL);
  m_stcEditor->SetMarginMask(2, ~(wxSTC_MASK_FOLDERS));
  m_stcEditor->SetMarginWidth(2, 0);
  m_stcEditor->SetMarginSensitive(2, true);

  // Configure the line numbers margin
  int m_stcEditor_PixelWidth =
      4 + 5 * m_stcEditor->TextWidth(wxSTC_STYLE_LINENUMBER, wxT("9"));
  m_stcEditor->SetMarginType(0, wxSTC_MARGIN_NUMBER);
  m_stcEditor->SetMarginWidth(0, m_stcEditor_PixelWidth);

  // Configure the line symbol margin
  m_stcEditor->SetMarginType(3, wxSTC_MARGIN_FORE);
  m_stcEditor->SetMarginMask(3, 0);
  m_stcEditor->SetMarginWidth(3, 1);
  // Select the lexer
  m_stcEditor->SetLexer(wxSTC_LEX_NULL);
  // Set default font / styles
  m_stcEditor->StyleClearAll();
  m_stcEditor->SetWrapMode(1);
  m_stcEditor->SetIndentationGuides(2);
  m_stcEditor->SetEOLMode(2);
  m_stcEditor->SetKeyWords(0, wxT(""));
  m_stcEditor->SetKeyWords(1, wxT(""));
  m_stcEditor->SetKeyWords(2, wxT(""));
  m_stcEditor->SetKeyWords(3, wxT(""));
  m_stcEditor->SetKeyWords(4, wxT(""));

  boxSizer35->Add(m_stcEditor, 1, wxEXPAND, WXC_FROM_DIP(5));

  SetName(wxT("EditFileDlgBase"));
  SetSize(wxDLG_UNIT(this, wxSize(500, 300)));
  if (GetSizer()) {
    GetSizer()->Fit(this);
  }
  if (GetParent()) {
    CentreOnParent(wxBOTH);
  } else {
    CentreOnScreen(wxBOTH);
  }
  if (!wxPersistenceManager::Get().Find(this)) {
    wxPersistenceManager::Get().RegisterAndRestore(this);
  } else {
    wxPersistenceManager::Get().Restore(this);
  }
}

EditFileDlgBase::~EditFileDlgBase() {}

EditHostsBase::EditHostsBase(wxWindow *parent, wxWindowID id,
                             const wxString &title, const wxPoint &pos,
                             const wxSize &size, long style)
    : wxDialog(parent, id, title, pos, size, style) {
  if (!bBitmapLoaded) {
    // We need to initialise the default bitmap handler
    wxXmlResource::Get()->AddHandler(new wxBitmapXmlHandler);
    wxCrafterFiTVkcInitBitmapResources();
    bBitmapLoaded = true;
  }

  wxBoxSizer *boxSizer48 = new wxBoxSizer(wxVERTICAL);
  this->SetSizer(boxSizer48);

  m_panel52 = new wxPanel(this, wxID_ANY, wxDefaultPosition,
                          wxDLG_UNIT(this, wxSize(-1, -1)), wxTAB_TRAVERSAL);

  boxSizer48->Add(m_panel52, 1, wxEXPAND, WXC_FROM_DIP(5));

  wxBoxSizer *boxSizer56 = new wxBoxSizer(wxVERTICAL);
  m_panel52->SetSizer(boxSizer56);

  wxBoxSizer *boxSizer57 = new wxBoxSizer(wxHORIZONTAL);

  boxSizer56->Add(boxSizer57, 1, wxALL | wxEXPAND, WXC_FROM_DIP(5));

  m_dvListCtrlHosts = new wxDataViewListCtrl(
      m_panel52, wxID_ANY, wxDefaultPosition,
      wxDLG_UNIT(m_panel52, wxSize(400, 200)), wxDV_ROW_LINES | wxDV_SINGLE);

  boxSizer57->Add(m_dvListCtrlHosts, 1, wxALL | wxEXPAND, WXC_FROM_DIP(5));

  m_dvListCtrlHosts->AppendTextColumn(_("Host Name"), wxDATAVIEW_CELL_INERT,
                                      WXC_FROM_DIP(200), wxALIGN_LEFT, 0);
  m_dvListCtrlHosts->AppendTextColumn(_("Address"), wxDATAVIEW_CELL_INERT,
                                      WXC_FROM_DIP(150), wxALIGN_LEFT,
                                      wxDATAVIEW_COL_RESIZABLE);
  wxBoxSizer *boxSizer59 = new wxBoxSizer(wxVERTICAL);

  boxSizer57->Add(boxSizer59, 0, wxEXPAND, WXC_FROM_DIP(5));

  m_buttonNew = new wxButton(m_panel52, wxID_NEW, _("&New"), wxDefaultPosition,
                             wxDLG_UNIT(m_panel52, wxSize(-1, -1)), 0);

  boxSizer59->Add(m_buttonNew, 0, wxALL | wxEXPAND, WXC_FROM_DIP(5));

  m_buttonDelete =
      new wxButton(m_panel52, wxID_DELETE, _("&Delete"), wxDefaultPosition,
                   wxDLG_UNIT(m_panel52, wxSize(-1, -1)), 0);

  boxSizer59->Add(m_buttonDelete, 0, wxALL | wxEXPAND, WXC_FROM_DIP(5));

  m_stdBtnSizer49 = new wxStdDialogButtonSizer();

  boxSizer48->Add(m_stdBtnSizer49, 0, wxALL | wxALIGN_CENTER_HORIZONTAL,
                  WXC_FROM_DIP(10));

  m_button50 = new wxButton(this, wxID_OK, wxT(""), wxDefaultPosition,
                            wxDLG_UNIT(this, wxSize(-1, -1)), 0);
  m_button50->SetDefault();
  m_stdBtnSizer49->AddButton(m_button50);

  m_button51 = new wxButton(this, wxID_CANCEL, wxT(""), wxDefaultPosition,
                            wxDLG_UNIT(this, wxSize(-1, -1)), 0);
  m_stdBtnSizer49->AddButton(m_button51);
  m_stdBtnSizer49->Realize();

  SetName(wxT("EditHostsBase"));
  SetSize(wxDLG_UNIT(this, wxSize(-1, -1)));
  if (GetSizer()) {
    GetSizer()->Fit(this);
  }
  if (GetParent()) {
    CentreOnParent(wxBOTH);
  } else {
    CentreOnScreen(wxBOTH);
  }
  if (!wxPersistenceManager::Get().Find(this)) {
    wxPersistenceManager::Get().RegisterAndRestore(this);
  } else {
    wxPersistenceManager::Get().Restore(this);
  }
  // Connect events
  m_dvListCtrlHosts->Bind(wxEVT_COMMAND_DATAVIEW_ITEM_ACTIVATED,
                          &EditHostsBase::OnHostActivated, this);
  m_dvListCtrlHosts->Bind(wxEVT_COMMAND_DATAVIEW_SELECTION_CHANGED,
                          &EditHostsBase::OnHostSelected, this);
  m_buttonNew->Bind(wxEVT_COMMAND_BUTTON_CLICKED, &EditHostsBase::OnNew, this);
  m_buttonDelete->Bind(wxEVT_COMMAND_BUTTON_CLICKED, &EditHostsBase::OnDelete,
                       this);
  m_buttonDelete->Bind(wxEVT_UPDATE_UI, &EditHostsBase::OnDeleteUI, this);
}

EditHostsBase::~EditHostsBase() {
  m_dvListCtrlHosts->Unbind(wxEVT_COMMAND_DATAVIEW_ITEM_ACTIVATED,
                            &EditHostsBase::OnHostActivated, this);
  m_dvListCtrlHosts->Unbind(wxEVT_COMMAND_DATAVIEW_SELECTION_CHANGED,
                            &EditHostsBase::OnHostSelected, this);
  m_buttonNew->Unbind(wxEVT_COMMAND_BUTTON_CLICKED, &EditHostsBase::OnNew,
                      this);
  m_buttonDelete->Unbind(wxEVT_COMMAND_BUTTON_CLICKED, &EditHostsBase::OnDelete,
                         this);
  m_buttonDelete->Unbind(wxEVT_UPDATE_UI, &EditHostsBase::OnDeleteUI, this);
}

EditAgentDlgBase::EditAgentDlgBase(wxWindow *parent, wxWindowID id,
                                   const wxString &title, const wxPoint &pos,
                                   const wxSize &size, long style)
    : wxDialog(parent, id, title, pos, size, style) {
  if (!bBitmapLoaded) {
    // We need to initialise the default bitmap handler
    wxXmlResource::Get()->AddHandler(new wxBitmapXmlHandler);
    wxCrafterFiTVkcInitBitmapResources();
    bBitmapLoaded = true;
  }

  wxBoxSizer *boxSizer74 = new wxBoxSizer(wxVERTICAL);
  this->SetSizer(boxSizer74);

  m_panel87 = new wxPanel(this, wxID_ANY, wxDefaultPosition,
                          wxDLG_UNIT(this, wxSize(-1, -1)), wxTAB_TRAVERSAL);

  boxSizer74->Add(m_panel87, 1, wxALL | wxEXPAND, WXC_FROM_DIP(5));

  wxBoxSizer *boxSizer88 = new wxBoxSizer(wxVERTICAL);
  m_panel87->SetSizer(boxSizer88);

  wxStaticBoxSizer *staticBoxSizer92 = new wxStaticBoxSizer(
      new wxStaticBox(m_panel87, wxID_ANY, _("General:")), wxVERTICAL);

  boxSizer88->Add(staticBoxSizer92, 0, wxALL | wxEXPAND, WXC_FROM_DIP(5));

  flexGridSizer82 = new wxFlexGridSizer(0, 2, 0, 0);
  flexGridSizer82->SetFlexibleDirection(wxBOTH);
  flexGridSizer82->SetNonFlexibleGrowMode(wxFLEX_GROWMODE_SPECIFIED);
  flexGridSizer82->AddGrowableCol(1);

  staticBoxSizer92->Add(flexGridSizer82, 0, wxALL | wxEXPAND, WXC_FROM_DIP(5));

  m_staticText83 =
      new wxStaticText(m_panel87, wxID_ANY, _("Name:"), wxDefaultPosition,
                       wxDLG_UNIT(m_panel87, wxSize(-1, -1)), 0);

  flexGridSizer82->Add(m_staticText83, 0,
                       wxALL | wxALIGN_RIGHT | wxALIGN_CENTER_VERTICAL,
                       WXC_FROM_DIP(5));

  m_textCtrlName =
      new wxTextCtrl(m_panel87, wxID_ANY, wxT(""), wxDefaultPosition,
                     wxDLG_UNIT(m_panel87, wxSize(350, -1)), 0);
  m_textCtrlName->SetFocus();
#if wxVERSION_NUMBER >= 3000
  m_textCtrlName->SetHint(wxT(""));
#endif

  flexGridSizer82->Add(m_textCtrlName, 0, wxALL | wxEXPAND, WXC_FROM_DIP(5));

  m_staticText295 =
      new wxStaticText(m_panel87, wxID_ANY, _("Executable:"), wxDefaultPosition,
                       wxDLG_UNIT(m_panel87, wxSize(-1, -1)), 0);

  flexGridSizer82->Add(m_staticText295, 0,
                       wxALL | wxALIGN_RIGHT | wxALIGN_CENTER_VERTICAL,
                       WXC_FROM_DIP(5));

  wxArrayString m_comboBoxExecutableArr;
  m_comboBoxExecutable = new wxComboBox(
      m_panel87, wxID_ANY, wxT(""), wxDefaultPosition,
      wxDLG_UNIT(m_panel87, wxSize(-1, -1)), m_comboBoxExecutableArr, 0);
#if wxVERSION_NUMBER >= 3000
  m_comboBoxExecutable->SetHint(wxT(""));
#endif

  flexGridSizer82->Add(m_comboBoxExecutable, 0, wxALL | wxEXPAND,
                       WXC_FROM_DIP(5));

  m_staticText89 = new wxStaticText(m_panel87, wxID_ANY, _("Launch Args:"),
                                    wxDefaultPosition,
                                    wxDLG_UNIT(m_panel87, wxSize(-1, -1)), 0);

  flexGridSizer82->Add(m_staticText89, 0,
                       wxALL | wxALIGN_RIGHT | wxALIGN_CENTER_VERTICAL,
                       WXC_FROM_DIP(5));

  m_textCtrlLaunchArgs =
      new wxTextCtrl(m_panel87, wxID_ANY, wxT(""), wxDefaultPosition,
                     wxDLG_UNIT(m_panel87, wxSize(-1, -1)), 0);
#if wxVERSION_NUMBER >= 3000
  m_textCtrlLaunchArgs->SetHint(_("e.g. --agent my-agent"));
#endif

  flexGridSizer82->Add(m_textCtrlLaunchArgs, 0, wxALL | wxEXPAND,
                       WXC_FROM_DIP(5));

  m_staticText293 = new wxStaticText(m_panel87, wxID_ANY, _("Resume Args:"),
                                     wxDefaultPosition,
                                     wxDLG_UNIT(m_panel87, wxSize(-1, -1)), 0);

  flexGridSizer82->Add(m_staticText293, 0,
                       wxALL | wxALIGN_RIGHT | wxALIGN_CENTER_VERTICAL,
                       WXC_FROM_DIP(5));

  wxBoxSizer *boxSizer330 = new wxBoxSizer(wxHORIZONTAL);

  flexGridSizer82->Add(boxSizer330, 0, wxEXPAND, WXC_FROM_DIP(5));

  m_textCtrlResumeArgs =
      new wxTextCtrl(m_panel87, wxID_ANY, wxT(""), wxDefaultPosition,
                     wxDLG_UNIT(m_panel87, wxSize(-1, -1)), 0);
#if wxVERSION_NUMBER >= 3000
  m_textCtrlResumeArgs->SetHint(_("e.g. --resume"));
#endif

  boxSizer330->Add(m_textCtrlResumeArgs, 1, wxALL | wxALIGN_CENTER_VERTICAL,
                   WXC_FROM_DIP(5));

  m_button331 =
      new wxButton(m_panel87, wxID_ANY, _("..."), wxDefaultPosition,
                   wxDLG_UNIT(m_panel87, wxSize(-1, -1)), wxBU_EXACTFIT);
  m_button331->SetToolTip(_("Suggest"));

  boxSizer330->Add(m_button331, 0, wxALL | wxALIGN_CENTER_VERTICAL,
                   WXC_FROM_DIP(5));

  m_staticText372 = new wxStaticText(m_panel87, wxID_ANY, _("Login Shell:"),
                                     wxDefaultPosition,
                                     wxDLG_UNIT(m_panel87, wxSize(-1, -1)), 0);

  flexGridSizer82->Add(m_staticText372, 0,
                       wxALL | wxALIGN_RIGHT | wxALIGN_CENTER_VERTICAL,
                       WXC_FROM_DIP(5));

  wxArrayString m_choiceShellArr;
  m_choiceShell =
      new wxChoice(m_panel87, wxID_ANY, wxDefaultPosition,
                   wxDLG_UNIT(m_panel87, wxSize(-1, -1)), m_choiceShellArr, 0);

  flexGridSizer82->Add(m_choiceShell, 0, wxALL | wxEXPAND, WXC_FROM_DIP(5));

  m_staticText99 =
      new wxStaticText(m_panel87, wxID_ANY, _("Image:"), wxDefaultPosition,
                       wxDLG_UNIT(m_panel87, wxSize(-1, -1)), 0);

  flexGridSizer82->Add(m_staticText99, 0,
                       wxALL | wxALIGN_RIGHT | wxALIGN_CENTER_VERTICAL,
                       WXC_FROM_DIP(5));

  wxBoxSizer *boxSizer154 = new wxBoxSizer(wxHORIZONTAL);

  flexGridSizer82->Add(boxSizer154, 1, wxEXPAND, WXC_FROM_DIP(5));

  m_textCtrlBitmap =
      new wxTextCtrl(m_panel87, wxID_ANY, wxT(""), wxDefaultPosition,
                     wxDLG_UNIT(m_panel87, wxSize(-1, -1)), 0);
#if wxVERSION_NUMBER >= 3000
  m_textCtrlBitmap->SetHint(wxT(""));
#endif

  boxSizer154->Add(m_textCtrlBitmap, 1, wxALL, WXC_FROM_DIP(5));

  m_button155 =
      new wxButton(m_panel87, wxID_ANY, _("..."), wxDefaultPosition,
                   wxDLG_UNIT(m_panel87, wxSize(-1, -1)), wxBU_EXACTFIT);

  boxSizer154->Add(m_button155, 0, wxALL | wxALIGN_CENTER_VERTICAL,
                   WXC_FROM_DIP(5));

  wxStaticBoxSizer *staticBoxSizer327 = new wxStaticBoxSizer(
      new wxStaticBox(m_panel87, wxID_ANY, _("Remote Setup (optional):")),
      wxVERTICAL);

  boxSizer88->Add(staticBoxSizer327, 0, wxALL | wxEXPAND, WXC_FROM_DIP(5));

  wxFlexGridSizer *flexGridSizer328 = new wxFlexGridSizer(0, 2, 0, 0);
  flexGridSizer328->SetFlexibleDirection(wxBOTH);
  flexGridSizer328->SetNonFlexibleGrowMode(wxFLEX_GROWMODE_SPECIFIED);
  flexGridSizer328->AddGrowableCol(1);

  staticBoxSizer327->Add(flexGridSizer328, 1, wxALL | wxEXPAND,
                         WXC_FROM_DIP(5));

  m_staticText289 = new wxStaticText(m_panel87, wxID_ANY, _("Remote Host:"),
                                     wxDefaultPosition,
                                     wxDLG_UNIT(m_panel87, wxSize(-1, -1)), 0);

  flexGridSizer328->Add(m_staticText289, 0,
                        wxALL | wxALIGN_RIGHT | wxALIGN_CENTER_VERTICAL,
                        WXC_FROM_DIP(5));

  wxFlexGridSizer *flexGridSizer324 = new wxFlexGridSizer(0, 4, 0, 0);
  flexGridSizer324->SetFlexibleDirection(wxBOTH);
  flexGridSizer324->SetNonFlexibleGrowMode(wxFLEX_GROWMODE_SPECIFIED);
  flexGridSizer324->AddGrowableCol(0);
  flexGridSizer324->AddGrowableCol(2);

  flexGridSizer328->Add(flexGridSizer324, 0, wxEXPAND, WXC_FROM_DIP(5));

  m_textCtrlHost =
      new wxTextCtrl(m_panel87, wxID_ANY, wxT(""), wxDefaultPosition,
                     wxDLG_UNIT(m_panel87, wxSize(-1, -1)), 0);
#if wxVERSION_NUMBER >= 3000
  m_textCtrlHost->SetHint(_("Optional: remote host"));
#endif

  flexGridSizer324->Add(m_textCtrlHost, 0,
                        wxALL | wxEXPAND | wxALIGN_CENTER_VERTICAL,
                        WXC_FROM_DIP(5));

  m_button292 =
      new wxButton(m_panel87, wxID_ANY, _("..."), wxDefaultPosition,
                   wxDLG_UNIT(m_panel87, wxSize(-1, -1)), wxBU_EXACTFIT);

  flexGridSizer324->Add(m_button292, 0, wxALL | wxALIGN_CENTER_VERTICAL,
                        WXC_FROM_DIP(5));

  m_staticText329 = new wxStaticText(m_panel87, wxID_ANY, _("Remote User:"),
                                     wxDefaultPosition,
                                     wxDLG_UNIT(m_panel87, wxSize(-1, -1)), 0);

  flexGridSizer328->Add(m_staticText329, 0,
                        wxALL | wxALIGN_RIGHT | wxALIGN_CENTER_VERTICAL,
                        WXC_FROM_DIP(5));

  m_textCtrlUser =
      new wxTextCtrl(m_panel87, wxID_ANY, wxT(""), wxDefaultPosition,
                     wxDLG_UNIT(m_panel87, wxSize(-1, -1)), 0);
#if wxVERSION_NUMBER >= 3000
  m_textCtrlUser->SetHint(_("Optional: remote user"));
#endif

  flexGridSizer328->Add(m_textCtrlUser, 0, wxALL | wxEXPAND, WXC_FROM_DIP(5));

  wxStaticBoxSizer *staticBoxSizer93 = new wxStaticBoxSizer(
      new wxStaticBox(m_panel87, wxID_ANY,
                      _("Environment Variables (optional):")),
      wxVERTICAL);

  boxSizer88->Add(staticBoxSizer93, 1, wxALL | wxEXPAND, WXC_FROM_DIP(5));

  wxBoxSizer *boxSizer95 = new wxBoxSizer(wxHORIZONTAL);

  staticBoxSizer93->Add(boxSizer95, 1, wxEXPAND, WXC_FROM_DIP(5));

  m_dvListCtrlEnv = new wxDataViewListCtrl(
      m_panel87, wxID_ANY, wxDefaultPosition,
      wxDLG_UNIT(m_panel87, wxSize(-1, 100)), wxDV_ROW_LINES | wxDV_SINGLE);

  boxSizer95->Add(m_dvListCtrlEnv, 1, wxALL | wxEXPAND, WXC_FROM_DIP(5));

  m_dvListCtrlEnv->AppendTextColumn(_("Name"), wxDATAVIEW_CELL_INERT,
                                    WXC_FROM_DIP(-2), wxALIGN_LEFT, 0);
  m_dvListCtrlEnv->AppendTextColumn(_("Value"), wxDATAVIEW_CELL_INERT,
                                    WXC_FROM_DIP(-2), wxALIGN_LEFT, 0);
  wxBoxSizer *boxSizer96 = new wxBoxSizer(wxVERTICAL);

  boxSizer95->Add(boxSizer96, 0, wxEXPAND, WXC_FROM_DIP(5));

  m_buttonNewEnv =
      new wxButton(m_panel87, wxID_ANY, _("New"), wxDefaultPosition,
                   wxDLG_UNIT(m_panel87, wxSize(-1, -1)), 0);

  boxSizer96->Add(m_buttonNewEnv, 0, wxALL | wxEXPAND, WXC_FROM_DIP(5));

  m_buttonDeleteEnv =
      new wxButton(m_panel87, wxID_ANY, _("Delete"), wxDefaultPosition,
                   wxDLG_UNIT(m_panel87, wxSize(-1, -1)), 0);

  boxSizer96->Add(m_buttonDeleteEnv, 0, wxALL | wxEXPAND, WXC_FROM_DIP(5));

  m_stdBtnSizer75 = new wxStdDialogButtonSizer();

  boxSizer74->Add(m_stdBtnSizer75, 0, wxALL | wxALIGN_CENTER_HORIZONTAL,
                  WXC_FROM_DIP(10));

  m_buttonOk = new wxButton(this, wxID_OK, wxT(""), wxDefaultPosition,
                            wxDLG_UNIT(this, wxSize(-1, -1)), 0);
  m_buttonOk->SetDefault();
  m_stdBtnSizer75->AddButton(m_buttonOk);

  m_buttonCancel = new wxButton(this, wxID_CANCEL, wxT(""), wxDefaultPosition,
                                wxDLG_UNIT(this, wxSize(-1, -1)), 0);
  m_stdBtnSizer75->AddButton(m_buttonCancel);
  m_stdBtnSizer75->Realize();

  SetName(wxT("EditAgentDlgBase"));
  SetSize(wxDLG_UNIT(this, wxSize(-1, -1)));
  if (GetSizer()) {
    GetSizer()->Fit(this);
  }
  if (GetParent()) {
    CentreOnParent(wxBOTH);
  } else {
    CentreOnScreen(wxBOTH);
  }
  if (!wxPersistenceManager::Get().Find(this)) {
    wxPersistenceManager::Get().RegisterAndRestore(this);
  } else {
    wxPersistenceManager::Get().Restore(this);
  }
  // Connect events
  m_button331->Bind(wxEVT_COMMAND_BUTTON_CLICKED,
                    &EditAgentDlgBase::OnSuggestResumeArgs, this);
  m_button155->Bind(wxEVT_COMMAND_BUTTON_CLICKED,
                    &EditAgentDlgBase::OnBrowseBitmap, this);
  m_button292->Bind(wxEVT_COMMAND_BUTTON_CLICKED,
                    &EditAgentDlgBase::OnRemoteHost, this);
  m_dvListCtrlEnv->Bind(wxEVT_COMMAND_DATAVIEW_ITEM_ACTIVATED,
                        &EditAgentDlgBase::OnEnvActivated, this);
  m_buttonNewEnv->Bind(wxEVT_COMMAND_BUTTON_CLICKED,
                       &EditAgentDlgBase::OnNewEnv, this);
  m_buttonDeleteEnv->Bind(wxEVT_COMMAND_BUTTON_CLICKED,
                          &EditAgentDlgBase::OnDeleteEnv, this);
  m_buttonDeleteEnv->Bind(wxEVT_UPDATE_UI, &EditAgentDlgBase::OnDeleteEnvUI,
                          this);
  m_buttonOk->Bind(wxEVT_UPDATE_UI, &EditAgentDlgBase::OnOkUI, this);
  m_buttonOk->Bind(wxEVT_COMMAND_BUTTON_CLICKED, &EditAgentDlgBase::OnOk, this);
}

EditAgentDlgBase::~EditAgentDlgBase() {
  m_button331->Unbind(wxEVT_COMMAND_BUTTON_CLICKED,
                      &EditAgentDlgBase::OnSuggestResumeArgs, this);
  m_button155->Unbind(wxEVT_COMMAND_BUTTON_CLICKED,
                      &EditAgentDlgBase::OnBrowseBitmap, this);
  m_button292->Unbind(wxEVT_COMMAND_BUTTON_CLICKED,
                      &EditAgentDlgBase::OnRemoteHost, this);
  m_dvListCtrlEnv->Unbind(wxEVT_COMMAND_DATAVIEW_ITEM_ACTIVATED,
                          &EditAgentDlgBase::OnEnvActivated, this);
  m_buttonNewEnv->Unbind(wxEVT_COMMAND_BUTTON_CLICKED,
                         &EditAgentDlgBase::OnNewEnv, this);
  m_buttonDeleteEnv->Unbind(wxEVT_COMMAND_BUTTON_CLICKED,
                            &EditAgentDlgBase::OnDeleteEnv, this);
  m_buttonDeleteEnv->Unbind(wxEVT_UPDATE_UI, &EditAgentDlgBase::OnDeleteEnvUI,
                            this);
  m_buttonOk->Unbind(wxEVT_UPDATE_UI, &EditAgentDlgBase::OnOkUI, this);
  m_buttonOk->Unbind(wxEVT_COMMAND_BUTTON_CLICKED, &EditAgentDlgBase::OnOk,
                     this);
}

EditAgentsDlgBase::EditAgentsDlgBase(wxWindow *parent, wxWindowID id,
                                     const wxString &title, const wxPoint &pos,
                                     const wxSize &size, long style)
    : wxDialog(parent, id, title, pos, size, style) {
  if (!bBitmapLoaded) {
    // We need to initialise the default bitmap handler
    wxXmlResource::Get()->AddHandler(new wxBitmapXmlHandler);
    wxCrafterFiTVkcInitBitmapResources();
    bBitmapLoaded = true;
  }

  wxBoxSizer *boxSizer102 = new wxBoxSizer(wxVERTICAL);
  this->SetSizer(boxSizer102);

  m_panel106 = new wxPanel(this, wxID_ANY, wxDefaultPosition,
                           wxDLG_UNIT(this, wxSize(-1, -1)), wxTAB_TRAVERSAL);

  boxSizer102->Add(m_panel106, 1, wxALL | wxEXPAND, WXC_FROM_DIP(5));

  wxBoxSizer *boxSizer107 = new wxBoxSizer(wxHORIZONTAL);
  m_panel106->SetSizer(boxSizer107);

  m_dvListCtrlAgents = new wxDataViewListCtrl(
      m_panel106, wxID_ANY, wxDefaultPosition,
      wxDLG_UNIT(m_panel106, wxSize(400, 200)), wxDV_ROW_LINES | wxDV_SINGLE);
  m_dvListCtrlAgents->SetFocus();

  boxSizer107->Add(m_dvListCtrlAgents, 1, wxALL | wxEXPAND, WXC_FROM_DIP(5));

  m_dvListCtrlAgents->AppendIconTextColumn(_("Agent Name"),
                                           wxDATAVIEW_CELL_INERT,
                                           WXC_FROM_DIP(-2), wxALIGN_LEFT, 0);
  wxBoxSizer *boxSizer110 = new wxBoxSizer(wxVERTICAL);

  boxSizer107->Add(boxSizer110, 0, wxEXPAND, WXC_FROM_DIP(5));

  m_buttonNew = new wxButton(m_panel106, wxID_ANY, _("New"), wxDefaultPosition,
                             wxDLG_UNIT(m_panel106, wxSize(-1, -1)), 0);

  boxSizer110->Add(m_buttonNew, 0, wxALL | wxEXPAND, WXC_FROM_DIP(5));

  m_buttonEdit =
      new wxButton(m_panel106, wxID_ANY, _("Edit"), wxDefaultPosition,
                   wxDLG_UNIT(m_panel106, wxSize(-1, -1)), 0);

  boxSizer110->Add(m_buttonEdit, 0, wxALL | wxEXPAND, WXC_FROM_DIP(5));

  m_buttonDelete =
      new wxButton(m_panel106, wxID_DELETE, _("Delete"), wxDefaultPosition,
                   wxDLG_UNIT(m_panel106, wxSize(-1, -1)), 0);

  boxSizer110->Add(m_buttonDelete, 0, wxALL | wxEXPAND, WXC_FROM_DIP(5));

  m_stdBtnSizer103 = new wxStdDialogButtonSizer();

  boxSizer102->Add(m_stdBtnSizer103, 0, wxALL | wxALIGN_CENTER_HORIZONTAL,
                   WXC_FROM_DIP(10));

  m_buttonOk = new wxButton(this, wxID_OK, wxT(""), wxDefaultPosition,
                            wxDLG_UNIT(this, wxSize(-1, -1)), 0);
  m_buttonOk->SetDefault();
  m_stdBtnSizer103->AddButton(m_buttonOk);

  m_buttonCancel = new wxButton(this, wxID_CANCEL, wxT(""), wxDefaultPosition,
                                wxDLG_UNIT(this, wxSize(-1, -1)), 0);
  m_stdBtnSizer103->AddButton(m_buttonCancel);
  m_stdBtnSizer103->Realize();

  SetName(wxT("EditAgentsDlgBase"));
  SetSize(wxDLG_UNIT(this, wxSize(-1, -1)));
  if (GetSizer()) {
    GetSizer()->Fit(this);
  }
  if (GetParent()) {
    CentreOnParent(wxBOTH);
  } else {
    CentreOnScreen(wxBOTH);
  }
  if (!wxPersistenceManager::Get().Find(this)) {
    wxPersistenceManager::Get().RegisterAndRestore(this);
  } else {
    wxPersistenceManager::Get().Restore(this);
  }
  // Connect events
  m_dvListCtrlAgents->Bind(wxEVT_COMMAND_DATAVIEW_ITEM_ACTIVATED,
                           &EditAgentsDlgBase::OnItemActivated, this);
  m_buttonNew->Bind(wxEVT_COMMAND_BUTTON_CLICKED,
                    &EditAgentsDlgBase::OnNewAgent, this);
  m_buttonEdit->Bind(wxEVT_COMMAND_BUTTON_CLICKED,
                     &EditAgentsDlgBase::OnEditAgent, this);
  m_buttonEdit->Bind(wxEVT_UPDATE_UI, &EditAgentsDlgBase::OnEditAgentUI, this);
  m_buttonDelete->Bind(wxEVT_COMMAND_BUTTON_CLICKED,
                       &EditAgentsDlgBase::OnDelete, this);
  m_buttonDelete->Bind(wxEVT_UPDATE_UI, &EditAgentsDlgBase::OnEditAgentUI,
                       this);
  m_buttonOk->Bind(wxEVT_COMMAND_BUTTON_CLICKED, &EditAgentsDlgBase::OnOK,
                   this);
}

EditAgentsDlgBase::~EditAgentsDlgBase() {
  m_dvListCtrlAgents->Unbind(wxEVT_COMMAND_DATAVIEW_ITEM_ACTIVATED,
                             &EditAgentsDlgBase::OnItemActivated, this);
  m_buttonNew->Unbind(wxEVT_COMMAND_BUTTON_CLICKED,
                      &EditAgentsDlgBase::OnNewAgent, this);
  m_buttonEdit->Unbind(wxEVT_COMMAND_BUTTON_CLICKED,
                       &EditAgentsDlgBase::OnEditAgent, this);
  m_buttonEdit->Unbind(wxEVT_UPDATE_UI, &EditAgentsDlgBase::OnEditAgentUI,
                       this);
  m_buttonDelete->Unbind(wxEVT_COMMAND_BUTTON_CLICKED,
                         &EditAgentsDlgBase::OnDelete, this);
  m_buttonDelete->Unbind(wxEVT_UPDATE_UI, &EditAgentsDlgBase::OnEditAgentUI,
                         this);
  m_buttonOk->Unbind(wxEVT_COMMAND_BUTTON_CLICKED, &EditAgentsDlgBase::OnOK,
                     this);
}

AboutDialogBase::AboutDialogBase(wxWindow *parent, wxWindowID id,
                                 const wxString &title, const wxPoint &pos,
                                 const wxSize &size, long style)
    : wxDialog(parent, id, title, pos, size, style) {
  if (!bBitmapLoaded) {
    // We need to initialise the default bitmap handler
    wxXmlResource::Get()->AddHandler(new wxBitmapXmlHandler);
    wxCrafterFiTVkcInitBitmapResources();
    bBitmapLoaded = true;
  }

  wxBoxSizer *boxSizer119 = new wxBoxSizer(wxVERTICAL);
  this->SetSizer(boxSizer119);

  m_panel123 = new wxPanel(this, wxID_ANY, wxDefaultPosition,
                           wxDLG_UNIT(this, wxSize(-1, -1)), wxTAB_TRAVERSAL);

  boxSizer119->Add(m_panel123, 1, wxALL | wxEXPAND, WXC_FROM_DIP(5));

  wxBoxSizer *boxSizer124 = new wxBoxSizer(wxVERTICAL);
  m_panel123->SetSizer(boxSizer124);

  m_notebook125 =
      new wxNotebook(m_panel123, wxID_ANY, wxDefaultPosition,
                     wxDLG_UNIT(m_panel123, wxSize(-1, -1)), wxBK_DEFAULT);
  m_notebook125->SetName(wxT("m_notebook125"));

  boxSizer124->Add(m_notebook125, 1, wxALL | wxEXPAND, WXC_FROM_DIP(5));

  m_panel126 =
      new wxPanel(m_notebook125, wxID_ANY, wxDefaultPosition,
                  wxDLG_UNIT(m_notebook125, wxSize(-1, -1)), wxTAB_TRAVERSAL);
  m_notebook125->AddPage(m_panel126, _("General"), true);

  wxBoxSizer *boxSizer140 = new wxBoxSizer(wxHORIZONTAL);
  m_panel126->SetSizer(boxSizer140);

  wxFlexGridSizer *flexGridSizer128 = new wxFlexGridSizer(0, 2, 0, 0);
  flexGridSizer128->SetFlexibleDirection(wxBOTH);
  flexGridSizer128->SetNonFlexibleGrowMode(wxFLEX_GROWMODE_SPECIFIED);
  flexGridSizer128->AddGrowableCol(1);

  boxSizer140->Add(flexGridSizer128, 0, wxALL | wxALIGN_CENTER_VERTICAL,
                   WXC_FROM_DIP(5));

  m_staticText129 = new wxStaticText(m_panel126, wxID_ANY, _("Application:"),
                                     wxDefaultPosition,
                                     wxDLG_UNIT(m_panel126, wxSize(-1, -1)), 0);

  flexGridSizer128->Add(m_staticText129, 0,
                        wxALL | wxALIGN_RIGHT | wxALIGN_CENTER_VERTICAL,
                        WXC_FROM_DIP(5));

  m_textCtrlName =
      new wxTextCtrl(m_panel126, wxID_ANY, wxT(""), wxDefaultPosition,
                     wxDLG_UNIT(m_panel126, wxSize(-1, -1)), 0);
#if wxVERSION_NUMBER >= 3000
  m_textCtrlName->SetHint(wxT(""));
#endif

  flexGridSizer128->Add(m_textCtrlName, 0, wxALL | wxEXPAND, WXC_FROM_DIP(5));

  m_staticText132 =
      new wxStaticText(m_panel126, wxID_ANY, _("Version:"), wxDefaultPosition,
                       wxDLG_UNIT(m_panel126, wxSize(-1, -1)), 0);

  flexGridSizer128->Add(m_staticText132, 0,
                        wxALL | wxALIGN_RIGHT | wxALIGN_CENTER_VERTICAL,
                        WXC_FROM_DIP(5));

  m_textCtrlVersion =
      new wxTextCtrl(m_panel126, wxID_ANY, wxT(""), wxDefaultPosition,
                     wxDLG_UNIT(m_panel126, wxSize(-1, -1)), 0);
#if wxVERSION_NUMBER >= 3000
  m_textCtrlVersion->SetHint(wxT(""));
#endif

  flexGridSizer128->Add(m_textCtrlVersion, 0, wxALL | wxEXPAND,
                        WXC_FROM_DIP(5));

  m_staticText134 =
      new wxStaticText(m_panel126, wxID_ANY, _("Author:"), wxDefaultPosition,
                       wxDLG_UNIT(m_panel126, wxSize(-1, -1)), 0);

  flexGridSizer128->Add(m_staticText134, 0,
                        wxALL | wxALIGN_RIGHT | wxALIGN_CENTER_VERTICAL,
                        WXC_FROM_DIP(5));

  m_textCtrlAuthor =
      new wxTextCtrl(m_panel126, wxID_ANY, wxT(""), wxDefaultPosition,
                     wxDLG_UNIT(m_panel126, wxSize(-1, -1)), 0);
#if wxVERSION_NUMBER >= 3000
  m_textCtrlAuthor->SetHint(wxT(""));
#endif

  flexGridSizer128->Add(m_textCtrlAuthor, 0, wxALL | wxEXPAND, WXC_FROM_DIP(5));

  m_staticText136 = new wxStaticText(m_panel126, wxID_ANY, _("Description:"),
                                     wxDefaultPosition,
                                     wxDLG_UNIT(m_panel126, wxSize(-1, -1)), 0);

  flexGridSizer128->Add(m_staticText136, 0,
                        wxALL | wxALIGN_RIGHT | wxALIGN_CENTER_VERTICAL,
                        WXC_FROM_DIP(5));

  m_textCtrlDescription =
      new wxTextCtrl(m_panel126, wxID_ANY, wxT(""), wxDefaultPosition,
                     wxDLG_UNIT(m_panel126, wxSize(250, -1)), 0);
#if wxVERSION_NUMBER >= 3000
  m_textCtrlDescription->SetHint(wxT(""));
#endif

  flexGridSizer128->Add(m_textCtrlDescription, 0, wxALL | wxEXPAND,
                        WXC_FROM_DIP(5));

  m_staticBitmapIcon =
      new wxStaticBitmap(m_panel126, wxID_ANY, wxNullBitmap, wxDefaultPosition,
                         wxDLG_UNIT(m_panel126, wxSize(-1, -1)), 0);

  boxSizer140->Add(m_staticBitmapIcon, 0,
                   wxALL | wxALIGN_CENTER_HORIZONTAL | wxALIGN_TOP,
                   WXC_FROM_DIP(5));

  m_panel127 =
      new wxPanel(m_notebook125, wxID_ANY, wxDefaultPosition,
                  wxDLG_UNIT(m_notebook125, wxSize(-1, -1)), wxTAB_TRAVERSAL);
  m_notebook125->AddPage(m_panel127, _("License"), false);

  wxBoxSizer *boxSizer138 = new wxBoxSizer(wxVERTICAL);
  m_panel127->SetSizer(boxSizer138);

  m_stcLicense =
      new wxStyledTextCtrl(m_panel127, wxID_ANY, wxDefaultPosition,
                           wxDLG_UNIT(m_panel127, wxSize(-1, -1)), 0);
  // Configure the fold margin
  m_stcLicense->SetMarginType(4, wxSTC_MARGIN_SYMBOL);
  m_stcLicense->SetMarginMask(4, wxSTC_MASK_FOLDERS);
  m_stcLicense->SetMarginSensitive(4, true);
  m_stcLicense->SetMarginWidth(4, 0);

  // Configure the tracker margin
  m_stcLicense->SetMarginWidth(1, 0);

  // Configure the symbol margin
  m_stcLicense->SetMarginType(2, wxSTC_MARGIN_SYMBOL);
  m_stcLicense->SetMarginMask(2, ~(wxSTC_MASK_FOLDERS));
  m_stcLicense->SetMarginWidth(2, 0);
  m_stcLicense->SetMarginSensitive(2, true);

  // Configure the line numbers margin
  m_stcLicense->SetMarginType(0, wxSTC_MARGIN_NUMBER);
  m_stcLicense->SetMarginWidth(0, 0);

  // Configure the line symbol margin
  m_stcLicense->SetMarginType(3, wxSTC_MARGIN_FORE);
  m_stcLicense->SetMarginMask(3, 0);
  m_stcLicense->SetMarginWidth(3, 0);
  // Select the lexer
  m_stcLicense->SetLexer(wxSTC_LEX_NULL);
  // Set default font / styles
  m_stcLicense->StyleClearAll();
  m_stcLicense->SetWrapMode(1);
  m_stcLicense->SetIndentationGuides(0);
  m_stcLicense->SetKeyWords(0, wxT(""));
  m_stcLicense->SetKeyWords(1, wxT(""));
  m_stcLicense->SetKeyWords(2, wxT(""));
  m_stcLicense->SetKeyWords(3, wxT(""));
  m_stcLicense->SetKeyWords(4, wxT(""));

  boxSizer138->Add(m_stcLicense, 1, wxALL | wxEXPAND, WXC_FROM_DIP(5));

  m_stdBtnSizer120 = new wxStdDialogButtonSizer();

  boxSizer119->Add(m_stdBtnSizer120, 0, wxALL | wxALIGN_CENTER_HORIZONTAL,
                   WXC_FROM_DIP(10));

  m_button121 = new wxButton(this, wxID_OK, wxT(""), wxDefaultPosition,
                             wxDLG_UNIT(this, wxSize(-1, -1)), 0);
  m_button121->SetDefault();
  m_stdBtnSizer120->AddButton(m_button121);
  m_stdBtnSizer120->Realize();

#if wxVERSION_NUMBER >= 2900
  if (!wxPersistenceManager::Get().Find(m_notebook125)) {
    wxPersistenceManager::Get().RegisterAndRestore(m_notebook125);
  } else {
    wxPersistenceManager::Get().Restore(m_notebook125);
  }
#endif

  SetName(wxT("AboutDialogBase"));
  SetSize(wxDLG_UNIT(this, wxSize(-1, -1)));
  if (GetSizer()) {
    GetSizer()->Fit(this);
  }
  if (GetParent()) {
    CentreOnParent(wxBOTH);
  } else {
    CentreOnScreen(wxBOTH);
  }
  if (!wxPersistenceManager::Get().Find(this)) {
    wxPersistenceManager::Get().RegisterAndRestore(this);
  } else {
    wxPersistenceManager::Get().Restore(this);
  }
}

AboutDialogBase::~AboutDialogBase() {}

FileBrowserDlgBase::FileBrowserDlgBase(wxWindow *parent, wxWindowID id,
                                       const wxString &title,
                                       const wxPoint &pos, const wxSize &size,
                                       long style)
    : wxDialog(parent, id, title, pos, size, style) {
  if (!bBitmapLoaded) {
    // We need to initialise the default bitmap handler
    wxXmlResource::Get()->AddHandler(new wxBitmapXmlHandler);
    wxCrafterFiTVkcInitBitmapResources();
    bBitmapLoaded = true;
  }

  wxBoxSizer *boxSizer298 = new wxBoxSizer(wxVERTICAL);
  this->SetSizer(boxSizer298);

  m_auibar = new wxAuiToolBar(
      this, wxID_ANY, wxDefaultPosition, wxDLG_UNIT(this, wxSize(-1, -1)),
      wxAUI_TB_PLAIN_BACKGROUND | wxAUI_TB_DEFAULT_STYLE);
  m_auibar->SetToolBitmapSize(wxSize(16, 16));

  boxSizer298->Add(m_auibar, 0, wxEXPAND, WXC_FROM_DIP(5));

  wxBoxSizer *boxSizer319 = new wxBoxSizer(wxVERTICAL);

  boxSizer298->Add(boxSizer319, 1, wxALL | wxEXPAND, WXC_FROM_DIP(5));

  m_panel320 = new wxPanel(this, wxID_ANY, wxDefaultPosition,
                           wxDLG_UNIT(this, wxSize(-1, -1)), wxTAB_TRAVERSAL);

  boxSizer319->Add(m_panel320, 1, wxEXPAND, WXC_FROM_DIP(5));

  wxBoxSizer *boxSizer321 = new wxBoxSizer(wxVERTICAL);
  m_panel320->SetSizer(boxSizer321);

  wxBoxSizer *boxSizer334 = new wxBoxSizer(wxHORIZONTAL);

  boxSizer321->Add(boxSizer334, 1, wxALL | wxEXPAND, WXC_FROM_DIP(5));

  m_dvListCtrl = new wxDataViewListCtrl(
      m_panel320, wxID_ANY, wxDefaultPosition,
      wxDLG_UNIT(m_panel320, wxSize(400, 300)), wxDV_ROW_LINES | wxDV_SINGLE);

  boxSizer334->Add(m_dvListCtrl, 3, wxALL | wxEXPAND, WXC_FROM_DIP(5));

  m_dvListCtrl->AppendIconTextColumn(_("Name"), wxDATAVIEW_CELL_INERT,
                                     WXC_FROM_DIP(250), wxALIGN_LEFT, 0);
  m_dvListCtrl->AppendTextColumn(_("Size"), wxDATAVIEW_CELL_INERT,
                                 WXC_FROM_DIP(50), wxALIGN_LEFT, 0);
  m_panelPreview =
      new wxPanel(m_panel320, wxID_ANY, wxDefaultPosition,
                  wxDLG_UNIT(m_panel320, wxSize(-1, -1)), wxTAB_TRAVERSAL);

  boxSizer334->Add(m_panelPreview, 0, wxALL | wxALIGN_CENTER_VERTICAL,
                   WXC_FROM_DIP(5));

  wxBoxSizer *boxSizer336 = new wxBoxSizer(wxVERTICAL);
  m_panelPreview->SetSizer(boxSizer336);

  m_staticBitmapPreview = new wxStaticBitmap(
      m_panelPreview, wxID_ANY, wxNullBitmap, wxDefaultPosition,
      wxDLG_UNIT(m_panelPreview, wxSize(64, 64)), 0);

  boxSizer336->Add(m_staticBitmapPreview, 1,
                   wxALL | wxEXPAND | wxALIGN_CENTER_HORIZONTAL,
                   WXC_FROM_DIP(5));

  wxFlexGridSizer *flexGridSizer332 = new wxFlexGridSizer(0, 3, 0, 0);
  flexGridSizer332->SetFlexibleDirection(wxBOTH);
  flexGridSizer332->SetNonFlexibleGrowMode(wxFLEX_GROWMODE_SPECIFIED);
  flexGridSizer332->AddGrowableCol(0);

  boxSizer321->Add(flexGridSizer332, 0, wxEXPAND, WXC_FROM_DIP(5));

  m_textCtrlCurrnentDir =
      new wxTextCtrl(m_panel320, wxID_ANY, wxT(""), wxDefaultPosition,
                     wxDLG_UNIT(m_panel320, wxSize(-1, -1)), wxTE_READONLY);
#if wxVERSION_NUMBER >= 3000
  m_textCtrlCurrnentDir->SetHint(wxT(""));
#endif

  flexGridSizer332->Add(m_textCtrlCurrnentDir, 0, wxALL | wxEXPAND,
                        WXC_FROM_DIP(5));

  m_button323 =
      new wxButton(m_panel320, wxID_ANY, _("Select"), wxDefaultPosition,
                   wxDLG_UNIT(m_panel320, wxSize(-1, -1)), 0);

  flexGridSizer332->Add(m_button323, 0, wxALL | wxALIGN_CENTER_VERTICAL,
                        WXC_FROM_DIP(5));

  SetName(wxT("FileBrowserDlgBase"));
  SetSize(wxDLG_UNIT(this, wxSize(-1, -1)));
  if (GetSizer()) {
    GetSizer()->Fit(this);
  }
  if (GetParent()) {
    CentreOnParent(wxBOTH);
  } else {
    CentreOnScreen(wxBOTH);
  }
  if (!wxPersistenceManager::Get().Find(this)) {
    wxPersistenceManager::Get().RegisterAndRestore(this);
  } else {
    wxPersistenceManager::Get().Restore(this);
  }
  // Connect events
  m_dvListCtrl->Bind(wxEVT_COMMAND_DATAVIEW_ITEM_ACTIVATED,
                     &FileBrowserDlgBase::OnActivated, this);
  m_dvListCtrl->Bind(wxEVT_KEY_DOWN, &FileBrowserDlgBase::OnKeyDown, this);
  m_dvListCtrl->Bind(wxEVT_COMMAND_DATAVIEW_SELECTION_CHANGED,
                     &FileBrowserDlgBase::OnSelectionChanged, this);
  m_button323->Bind(wxEVT_COMMAND_BUTTON_CLICKED, &FileBrowserDlgBase::OnSelect,
                    this);
  m_button323->Bind(wxEVT_UPDATE_UI, &FileBrowserDlgBase::OnSelectUI, this);
}

FileBrowserDlgBase::~FileBrowserDlgBase() {
  m_dvListCtrl->Unbind(wxEVT_COMMAND_DATAVIEW_ITEM_ACTIVATED,
                       &FileBrowserDlgBase::OnActivated, this);
  m_dvListCtrl->Unbind(wxEVT_KEY_DOWN, &FileBrowserDlgBase::OnKeyDown, this);
  m_dvListCtrl->Unbind(wxEVT_COMMAND_DATAVIEW_SELECTION_CHANGED,
                       &FileBrowserDlgBase::OnSelectionChanged, this);
  m_button323->Unbind(wxEVT_COMMAND_BUTTON_CLICKED,
                      &FileBrowserDlgBase::OnSelect, this);
  m_button323->Unbind(wxEVT_UPDATE_UI, &FileBrowserDlgBase::OnSelectUI, this);
}

NewEnvVarDlgBase::NewEnvVarDlgBase(wxWindow *parent, wxWindowID id,
                                   const wxString &title, const wxPoint &pos,
                                   const wxSize &size, long style)
    : wxDialog(parent, id, title, pos, size, style) {
  if (!bBitmapLoaded) {
    // We need to initialise the default bitmap handler
    wxXmlResource::Get()->AddHandler(new wxBitmapXmlHandler);
    wxCrafterFiTVkcInitBitmapResources();
    bBitmapLoaded = true;
  }

  wxBoxSizer *boxSizer307 = new wxBoxSizer(wxVERTICAL);
  this->SetSizer(boxSizer307);

  wxStaticBoxSizer *staticBoxSizer316 = new wxStaticBoxSizer(
      new wxStaticBox(this, wxID_ANY, wxT("")), wxVERTICAL);

  boxSizer307->Add(staticBoxSizer316, 1, wxALL | wxEXPAND, WXC_FROM_DIP(10));

  wxFlexGridSizer *flexGridSizer311 = new wxFlexGridSizer(0, 2, 0, 0);
  flexGridSizer311->SetFlexibleDirection(wxBOTH);
  flexGridSizer311->SetNonFlexibleGrowMode(wxFLEX_GROWMODE_SPECIFIED);
  flexGridSizer311->AddGrowableCol(1);

  staticBoxSizer316->Add(flexGridSizer311, 1, wxALL | wxEXPAND,
                         WXC_FROM_DIP(5));

  m_staticText312 =
      new wxStaticText(this, wxID_ANY, _("Name:"), wxDefaultPosition,
                       wxDLG_UNIT(this, wxSize(-1, -1)), 0);

  flexGridSizer311->Add(m_staticText312, 0,
                        wxALL | wxALIGN_RIGHT | wxALIGN_CENTER_VERTICAL,
                        WXC_FROM_DIP(5));

  m_textCtrlName = new wxTextCtrl(this, wxID_ANY, wxT(""), wxDefaultPosition,
                                  wxDLG_UNIT(this, wxSize(300, -1)), 0);
  m_textCtrlName->SetFocus();
#if wxVERSION_NUMBER >= 3000
  m_textCtrlName->SetHint(wxT(""));
#endif

  flexGridSizer311->Add(m_textCtrlName, 0, wxALL | wxEXPAND, WXC_FROM_DIP(5));

  m_staticText314 =
      new wxStaticText(this, wxID_ANY, _("Value:"), wxDefaultPosition,
                       wxDLG_UNIT(this, wxSize(-1, -1)), 0);

  flexGridSizer311->Add(m_staticText314, 0,
                        wxALL | wxALIGN_RIGHT | wxALIGN_CENTER_VERTICAL,
                        WXC_FROM_DIP(5));

  m_textCtrlValue = new wxTextCtrl(this, wxID_ANY, wxT(""), wxDefaultPosition,
                                   wxDLG_UNIT(this, wxSize(-1, -1)), 0);
#if wxVERSION_NUMBER >= 3000
  m_textCtrlValue->SetHint(wxT(""));
#endif

  flexGridSizer311->Add(m_textCtrlValue, 0, wxALL | wxEXPAND, WXC_FROM_DIP(5));

  m_stdBtnSizer308 = new wxStdDialogButtonSizer();

  boxSizer307->Add(m_stdBtnSizer308, 0, wxALL | wxALIGN_CENTER_HORIZONTAL,
                   WXC_FROM_DIP(10));

  m_buttonOK = new wxButton(this, wxID_OK, wxT(""), wxDefaultPosition,
                            wxDLG_UNIT(this, wxSize(-1, -1)), 0);
  m_buttonOK->SetDefault();
  m_stdBtnSizer308->AddButton(m_buttonOK);

  m_buttonCancel = new wxButton(this, wxID_CANCEL, wxT(""), wxDefaultPosition,
                                wxDLG_UNIT(this, wxSize(-1, -1)), 0);
  m_stdBtnSizer308->AddButton(m_buttonCancel);
  m_stdBtnSizer308->Realize();

  SetName(wxT("NewEnvVarDlgBase"));
  SetSize(wxDLG_UNIT(this, wxSize(-1, -1)));
  if (GetSizer()) {
    GetSizer()->Fit(this);
  }
  if (GetParent()) {
    CentreOnParent(wxBOTH);
  } else {
    CentreOnScreen(wxBOTH);
  }
  if (!wxPersistenceManager::Get().Find(this)) {
    wxPersistenceManager::Get().RegisterAndRestore(this);
  } else {
    wxPersistenceManager::Get().Restore(this);
  }
  // Connect events
  m_buttonOK->Bind(wxEVT_UPDATE_UI, &NewEnvVarDlgBase::OnOkUI, this);
}

NewEnvVarDlgBase::~NewEnvVarDlgBase() {
  m_buttonOK->Unbind(wxEVT_UPDATE_UI, &NewEnvVarDlgBase::OnOkUI, this);
}

SettingsDlgBase::SettingsDlgBase(wxWindow *parent, wxWindowID id,
                                 const wxString &title, const wxPoint &pos,
                                 const wxSize &size, long style)
    : wxDialog(parent, id, title, pos, size, style) {
  if (!bBitmapLoaded) {
    // We need to initialise the default bitmap handler
    wxXmlResource::Get()->AddHandler(new wxBitmapXmlHandler);
    wxCrafterFiTVkcInitBitmapResources();
    bBitmapLoaded = true;
  }

  wxBoxSizer *boxSizer346 = new wxBoxSizer(wxVERTICAL);
  this->SetSizer(boxSizer346);

  m_panel350 = new wxPanel(this, wxID_ANY, wxDefaultPosition,
                           wxDLG_UNIT(this, wxSize(-1, -1)), wxTAB_TRAVERSAL);

  boxSizer346->Add(m_panel350, 1, wxEXPAND, WXC_FROM_DIP(5));

  wxBoxSizer *boxSizer351 = new wxBoxSizer(wxVERTICAL);
  m_panel350->SetSizer(boxSizer351);

  m_notebook352 =
      new wxNotebook(m_panel350, wxID_ANY, wxDefaultPosition,
                     wxDLG_UNIT(m_panel350, wxSize(-1, -1)), wxBK_DEFAULT);
  m_notebook352->SetName(wxT("m_notebook352"));

  boxSizer351->Add(m_notebook352, 1, wxALL | wxEXPAND, WXC_FROM_DIP(5));

  m_panel353 =
      new wxPanel(m_notebook352, wxID_ANY, wxDefaultPosition,
                  wxDLG_UNIT(m_notebook352, wxSize(-1, -1)), wxTAB_TRAVERSAL);
  m_notebook352->AddPage(m_panel353, _("Appearance"), true);

  wxBoxSizer *boxSizer360 = new wxBoxSizer(wxVERTICAL);
  m_panel353->SetSizer(boxSizer360);

  wxStaticBoxSizer *staticBoxSizer359 = new wxStaticBoxSizer(
      new wxStaticBox(m_panel353, wxID_ANY, _("Colours and Fonts:")),
      wxVERTICAL);

  boxSizer360->Add(staticBoxSizer359, 1, wxALL | wxEXPAND, WXC_FROM_DIP(5));

  wxFlexGridSizer *flexGridSizer354 = new wxFlexGridSizer(0, 2, 0, 0);
  flexGridSizer354->SetFlexibleDirection(wxBOTH);
  flexGridSizer354->SetNonFlexibleGrowMode(wxFLEX_GROWMODE_SPECIFIED);
  flexGridSizer354->AddGrowableCol(1);

  staticBoxSizer359->Add(flexGridSizer354, 1, wxALL | wxEXPAND,
                         WXC_FROM_DIP(10));

  m_staticText355 =
      new wxStaticText(m_panel353, wxID_ANY, _("Theme:"), wxDefaultPosition,
                       wxDLG_UNIT(m_panel353, wxSize(-1, -1)), 0);

  flexGridSizer354->Add(m_staticText355, 0,
                        wxALL | wxALIGN_RIGHT | wxALIGN_CENTER_VERTICAL,
                        WXC_FROM_DIP(5));

  wxArrayString m_choiceThemeArr;
  m_choiceTheme = new wxChoice(m_panel353, wxID_ANY, wxDefaultPosition,
                               wxDLG_UNIT(m_panel353, wxSize(250, -1)),
                               m_choiceThemeArr, 0);

  flexGridSizer354->Add(m_choiceTheme, 0, wxALL | wxEXPAND, WXC_FROM_DIP(5));

  m_staticText357 = new wxStaticText(m_panel353, wxID_ANY, _("Terminal Font:"),
                                     wxDefaultPosition,
                                     wxDLG_UNIT(m_panel353, wxSize(-1, -1)), 0);

  flexGridSizer354->Add(m_staticText357, 0,
                        wxALL | wxALIGN_RIGHT | wxALIGN_CENTER_VERTICAL,
                        WXC_FROM_DIP(5));

  m_fontPicker = new wxFontPickerCtrl(
      m_panel353, wxID_ANY, wxNullFont, wxDefaultPosition,
      wxDLG_UNIT(m_panel353, wxSize(-1, -1)), wxFNTP_DEFAULT_STYLE);

  flexGridSizer354->Add(m_fontPicker, 0, wxALL | wxEXPAND, WXC_FROM_DIP(5));

  m_panel361 =
      new wxPanel(m_notebook352, wxID_ANY, wxDefaultPosition,
                  wxDLG_UNIT(m_notebook352, wxSize(-1, -1)), wxTAB_TRAVERSAL);
  m_notebook352->AddPage(m_panel361, _("General"), false);

  wxBoxSizer *boxSizer367 = new wxBoxSizer(wxVERTICAL);
  m_panel361->SetSizer(boxSizer367);

  wxStaticBoxSizer *staticBoxSizer363 = new wxStaticBoxSizer(
      new wxStaticBox(m_panel361, wxID_ANY, _("Terminal:")), wxVERTICAL);

  boxSizer367->Add(staticBoxSizer363, 0, wxALL | wxEXPAND, WXC_FROM_DIP(5));

  wxBoxSizer *boxSizer362 = new wxBoxSizer(wxVERTICAL);

  staticBoxSizer363->Add(boxSizer362, 1, wxEXPAND, WXC_FROM_DIP(5));

  wxFlexGridSizer *flexGridSizer364 = new wxFlexGridSizer(0, 2, 0, 0);
  flexGridSizer364->SetFlexibleDirection(wxBOTH);
  flexGridSizer364->SetNonFlexibleGrowMode(wxFLEX_GROWMODE_SPECIFIED);
  flexGridSizer364->AddGrowableCol(1);

  boxSizer362->Add(flexGridSizer364, 1, wxALL | wxEXPAND, WXC_FROM_DIP(10));

  m_staticText365 = new wxStaticText(
      m_panel361, wxID_ANY, _("Default Login Shell:"), wxDefaultPosition,
      wxDLG_UNIT(m_panel361, wxSize(-1, -1)), 0);

  flexGridSizer364->Add(m_staticText365, 0,
                        wxALL | wxALIGN_RIGHT | wxALIGN_CENTER_VERTICAL,
                        WXC_FROM_DIP(5));

  wxArrayString m_choiceShellArr;
  m_choiceShell = new wxChoice(m_panel361, wxID_ANY, wxDefaultPosition,
                               wxDLG_UNIT(m_panel361, wxSize(250, -1)),
                               m_choiceShellArr, 0);

  flexGridSizer364->Add(m_choiceShell, 0, wxALL | wxEXPAND, WXC_FROM_DIP(5));

  m_staticText498 = new wxStaticText(
      m_panel361, wxID_ANY, _("Default Home Directory:"), wxDefaultPosition,
      wxDLG_UNIT(m_panel361, wxSize(-1, -1)), 0);

  flexGridSizer364->Add(m_staticText498, 0,
                        wxALL | wxALIGN_RIGHT | wxALIGN_CENTER_VERTICAL,
                        WXC_FROM_DIP(5));

  m_dirPickerShellHomeDir = new wxDirPickerCtrl(
      m_panel361, wxID_ANY, wxEmptyString, _("Select a folder"),
      wxDefaultPosition, wxDLG_UNIT(m_panel361, wxSize(-1, -1)),
      wxDIRP_SMALL | wxDIRP_DEFAULT_STYLE);

  flexGridSizer364->Add(m_dirPickerShellHomeDir, 0, wxALL | wxEXPAND,
                        WXC_FROM_DIP(5));

  m_staticText504 = new wxStaticText(m_panel361, wxID_ANY,
                                     _("Scrollback Lines:"), wxDefaultPosition,
                                     wxDLG_UNIT(m_panel361, wxSize(-1, -1)), 0);

  flexGridSizer364->Add(m_staticText504, 0,
                        wxALL | wxALIGN_RIGHT | wxALIGN_CENTER_VERTICAL,
                        WXC_FROM_DIP(5));

  m_spinCtrlScrollBackLines =
      new wxSpinCtrl(m_panel361, wxID_ANY, wxT("5000"), wxDefaultPosition,
                     wxDLG_UNIT(m_panel361, wxSize(-1, -1)), wxSP_ARROW_KEYS);
  m_spinCtrlScrollBackLines->SetRange(1000, 100000);
  m_spinCtrlScrollBackLines->SetValue(5000);

  flexGridSizer364->Add(m_spinCtrlScrollBackLines, 0, wxALL, WXC_FROM_DIP(5));

  flexGridSizer364->Add(0, 0, 1, wxALL, WXC_FROM_DIP(5));

  m_checkBoxBlockCaret = new wxCheckBox(
      m_panel361, wxID_ANY, _("Use Block Caret"), wxDefaultPosition,
      wxDLG_UNIT(m_panel361, wxSize(-1, -1)), 0);
  m_checkBoxBlockCaret->SetValue(true);

  flexGridSizer364->Add(m_checkBoxBlockCaret, 0, wxALL, WXC_FROM_DIP(5));

  flexGridSizer364->Add(0, 0, 1, wxALL, WXC_FROM_DIP(5));

  m_checkBoxOptimizeDrawings = new wxCheckBox(
      m_panel361, wxID_ANY, _("Enable Optimize Drawings"), wxDefaultPosition,
      wxDLG_UNIT(m_panel361, wxSize(-1, -1)), 0);
  m_checkBoxOptimizeDrawings->SetValue(false);
  m_checkBoxOptimizeDrawings->SetToolTip(
      _("On platforms where OpenGL is not enabled, check this for better "
        "terminal drawing performance."));

  flexGridSizer364->Add(m_checkBoxOptimizeDrawings, 0, wxALL | wxEXPAND,
                        WXC_FROM_DIP(5));

  wxStaticBoxSizer *staticBoxSizer502 = new wxStaticBoxSizer(
      new wxStaticBox(m_panel361, wxID_ANY, _("Misc:")), wxVERTICAL);

  boxSizer367->Add(staticBoxSizer502, 0, wxALL | wxEXPAND, WXC_FROM_DIP(5));

  m_checkBoxForNewVersionOnStartup = new wxCheckBox(
      m_panel361, wxID_ANY, _("Check for new version on startup"),
      wxDefaultPosition, wxDLG_UNIT(m_panel361, wxSize(-1, -1)), 0);
  m_checkBoxForNewVersionOnStartup->SetValue(true);

  staticBoxSizer502->Add(m_checkBoxForNewVersionOnStartup, 0, wxALL,
                         WXC_FROM_DIP(5));

  m_stdBtnSizer347 = new wxStdDialogButtonSizer();

  boxSizer346->Add(m_stdBtnSizer347, 0, wxALL | wxALIGN_CENTER_HORIZONTAL,
                   WXC_FROM_DIP(10));

  m_buttonOk = new wxButton(this, wxID_OK, wxT(""), wxDefaultPosition,
                            wxDLG_UNIT(this, wxSize(-1, -1)), 0);
  m_buttonOk->SetDefault();
  m_stdBtnSizer347->AddButton(m_buttonOk);

  m_buttonCancel = new wxButton(this, wxID_CANCEL, wxT(""), wxDefaultPosition,
                                wxDLG_UNIT(this, wxSize(-1, -1)), 0);
  m_stdBtnSizer347->AddButton(m_buttonCancel);
  m_stdBtnSizer347->Realize();

#if wxVERSION_NUMBER >= 2900
  if (!wxPersistenceManager::Get().Find(m_notebook352)) {
    wxPersistenceManager::Get().RegisterAndRestore(m_notebook352);
  } else {
    wxPersistenceManager::Get().Restore(m_notebook352);
  }
#endif

  SetName(wxT("SettingsDlgBase"));
  SetSize(wxDLG_UNIT(this, wxSize(-1, -1)));
  if (GetSizer()) {
    GetSizer()->Fit(this);
  }
  if (GetParent()) {
    CentreOnParent(wxBOTH);
  } else {
    CentreOnScreen(wxBOTH);
  }
  if (!wxPersistenceManager::Get().Find(this)) {
    wxPersistenceManager::Get().RegisterAndRestore(this);
  } else {
    wxPersistenceManager::Get().Restore(this);
  }
  // Connect events
  m_choiceTheme->Bind(wxEVT_COMMAND_CHOICE_SELECTED,
                      &SettingsDlgBase::OnChoiceTheme, this);
  m_fontPicker->Bind(wxEVT_COMMAND_FONTPICKER_CHANGED,
                     &SettingsDlgBase::OnFontSelected, this);
}

SettingsDlgBase::~SettingsDlgBase() {
  m_choiceTheme->Unbind(wxEVT_COMMAND_CHOICE_SELECTED,
                        &SettingsDlgBase::OnChoiceTheme, this);
  m_fontPicker->Unbind(wxEVT_COMMAND_FONTPICKER_CHANGED,
                       &SettingsDlgBase::OnFontSelected, this);
}

NewAgentWizardBase::NewAgentWizardBase(wxWindow *parent, wxWindowID id,
                                       const wxString &title,
                                       const wxBitmap &bmp, const wxPoint &pos,
                                       long style) {
  if (!bBitmapLoaded) {
    // We need to initialise the default bitmap handler
    wxXmlResource::Get()->AddHandler(new wxBitmapXmlHandler);
    wxCrafterFiTVkcInitBitmapResources();
    bBitmapLoaded = true;
  }
  Create(parent, id, title, wxNullBitmap, pos, style);

  m_wizardPageLocalOrRemote =
      new wxWizardPageSimple(this, NULL, NULL, wxNullBitmap);
  m_pages.push_back(m_wizardPageLocalOrRemote);

  wxBoxSizer *boxSizer494 = new wxBoxSizer(wxHORIZONTAL);
  m_wizardPageLocalOrRemote->SetSizer(boxSizer494);

  m_bannerLocalOrRemoteBitmap = new wxBannerWindow(
      m_wizardPageLocalOrRemote, wxID_ANY, wxLEFT, wxDefaultPosition,
      wxDLG_UNIT(m_wizardPageLocalOrRemote, wxSize(-1, -1)), 0);
  m_bannerLocalOrRemoteBitmap->SetBitmap(wxNullBitmap);
  m_bannerLocalOrRemoteBitmap->SetText(wxT(""), wxT(""));

  boxSizer494->Add(m_bannerLocalOrRemoteBitmap, 0,
                   wxALL | wxEXPAND | wxALIGN_LEFT, WXC_FROM_DIP(5));

  wxBoxSizer *boxSizer383 = new wxBoxSizer(wxVERTICAL);

  boxSizer494->Add(boxSizer383, 1, wxALL | wxEXPAND, WXC_FROM_DIP(5));

  m_banner473 = new wxBannerWindow(
      m_wizardPageLocalOrRemote, wxID_ANY, wxTOP, wxDefaultPosition,
      wxDLG_UNIT(m_wizardPageLocalOrRemote, wxSize(-1, -1)), 0);
  m_banner473->SetBitmap(wxNullBitmap);
  m_banner473->SetText(
      _("Local or Remote?"),
      _("Select the environment where your AI agent will be launched."));
  m_banner473->SetGradient(wxSystemSettings::GetColour(wxSYS_COLOUR_BTNFACE),
                           wxSystemSettings::GetColour(wxSYS_COLOUR_BTNFACE));
  m_banner473->SetForegroundColour(
      wxSystemSettings::GetColour(wxSYS_COLOUR_BTNTEXT));

  boxSizer383->Add(m_banner473, 0, wxALL | wxEXPAND, WXC_FROM_DIP(5));

  m_checkBoxLocalHost =
      new wxCheckBox(m_wizardPageLocalOrRemote, wxID_ANY,
                     _("This is a local agent"), wxDefaultPosition,
                     wxDLG_UNIT(m_wizardPageLocalOrRemote, wxSize(-1, -1)), 0);
  m_checkBoxLocalHost->SetValue(true);

  boxSizer383->Add(m_checkBoxLocalHost, 0, wxALL | wxEXPAND, WXC_FROM_DIP(5));

  wxStaticBoxSizer *staticBoxSizer488 = new wxStaticBoxSizer(
      new wxStaticBox(m_wizardPageLocalOrRemote, wxID_ANY, _("Remote Host:")),
      wxVERTICAL);

  boxSizer383->Add(staticBoxSizer488, 0, wxALL | wxEXPAND, WXC_FROM_DIP(5));

  wxFlexGridSizer *flexGridSizer32829 = new wxFlexGridSizer(0, 2, 0, 0);
  flexGridSizer32829->SetFlexibleDirection(wxBOTH);
  flexGridSizer32829->SetNonFlexibleGrowMode(wxFLEX_GROWMODE_SPECIFIED);
  flexGridSizer32829->AddGrowableCol(1);

  staticBoxSizer488->Add(flexGridSizer32829, 1, wxALL | wxEXPAND,
                         WXC_FROM_DIP(5));

  m_staticText28930 = new wxStaticText(
      m_wizardPageLocalOrRemote, wxID_ANY, _("Host:"), wxDefaultPosition,
      wxDLG_UNIT(m_wizardPageLocalOrRemote, wxSize(-1, -1)), 0);

  flexGridSizer32829->Add(m_staticText28930, 0,
                          wxALL | wxALIGN_RIGHT | wxALIGN_CENTER_VERTICAL,
                          WXC_FROM_DIP(5));

  wxFlexGridSizer *flexGridSizer32431 = new wxFlexGridSizer(0, 4, 0, 0);
  flexGridSizer32431->SetFlexibleDirection(wxBOTH);
  flexGridSizer32431->SetNonFlexibleGrowMode(wxFLEX_GROWMODE_SPECIFIED);
  flexGridSizer32431->AddGrowableCol(0);
  flexGridSizer32431->AddGrowableCol(2);

  flexGridSizer32829->Add(flexGridSizer32431, 0, wxEXPAND, WXC_FROM_DIP(5));

  m_textCtrlHost = new wxTextCtrl(
      m_wizardPageLocalOrRemote, wxID_ANY, wxT(""), wxDefaultPosition,
      wxDLG_UNIT(m_wizardPageLocalOrRemote, wxSize(-1, -1)), 0);
  m_textCtrlHost->SetFocus();
#if wxVERSION_NUMBER >= 3000
  m_textCtrlHost->SetHint(_("Optional: remote host"));
#endif

  flexGridSizer32431->Add(m_textCtrlHost, 0,
                          wxALL | wxEXPAND | wxALIGN_CENTER_VERTICAL,
                          WXC_FROM_DIP(5));

  m_button29233 = new wxButton(
      m_wizardPageLocalOrRemote, wxID_ANY, _("..."), wxDefaultPosition,
      wxDLG_UNIT(m_wizardPageLocalOrRemote, wxSize(-1, -1)), wxBU_EXACTFIT);

  flexGridSizer32431->Add(m_button29233, 0, wxALL | wxALIGN_CENTER_VERTICAL,
                          WXC_FROM_DIP(5));

  m_staticText32934 = new wxStaticText(
      m_wizardPageLocalOrRemote, wxID_ANY, _("User:"), wxDefaultPosition,
      wxDLG_UNIT(m_wizardPageLocalOrRemote, wxSize(-1, -1)), 0);

  flexGridSizer32829->Add(m_staticText32934, 0,
                          wxALL | wxALIGN_RIGHT | wxALIGN_CENTER_VERTICAL,
                          WXC_FROM_DIP(5));

  m_textCtrlUser = new wxTextCtrl(
      m_wizardPageLocalOrRemote, wxID_ANY, wxT(""), wxDefaultPosition,
      wxDLG_UNIT(m_wizardPageLocalOrRemote, wxSize(-1, -1)), 0);
#if wxVERSION_NUMBER >= 3000
  m_textCtrlUser->SetHint(_("Optional: remote user"));
#endif

  flexGridSizer32829->Add(m_textCtrlUser, 0, wxALL | wxEXPAND, WXC_FROM_DIP(5));

  m_wizardPageWhatToLaunch =
      new wxWizardPageSimple(this, NULL, NULL, wxNullBitmap);
  m_pages.push_back(m_wizardPageWhatToLaunch);

  wxBoxSizer *boxSizer492 = new wxBoxSizer(wxHORIZONTAL);
  m_wizardPageWhatToLaunch->SetSizer(boxSizer492);

  m_bannerWhatToLaunchBitmap = new wxBannerWindow(
      m_wizardPageWhatToLaunch, wxID_ANY, wxLEFT, wxDefaultPosition,
      wxDLG_UNIT(m_wizardPageWhatToLaunch, wxSize(-1, -1)), 0);
  m_bannerWhatToLaunchBitmap->SetBitmap(wxNullBitmap);
  m_bannerWhatToLaunchBitmap->SetText(wxT(""), wxT(""));

  boxSizer492->Add(m_bannerWhatToLaunchBitmap, 0, wxALL | wxEXPAND,
                   WXC_FROM_DIP(5));

  wxBoxSizer *boxSizer382 = new wxBoxSizer(wxVERTICAL);

  boxSizer492->Add(boxSizer382, 1, wxALL | wxEXPAND, WXC_FROM_DIP(5));

  m_banner436 = new wxBannerWindow(
      m_wizardPageWhatToLaunch, wxID_ANY, wxTOP, wxDefaultPosition,
      wxDLG_UNIT(m_wizardPageWhatToLaunch, wxSize(-1, -1)), 0);
  m_banner436->SetBitmap(wxNullBitmap);
  m_banner436->SetText(_("What to launch"),
                       _("Configure the command, arguments, and visual "
                         "appearance of the agent."));
  m_banner436->SetGradient(wxSystemSettings::GetColour(wxSYS_COLOUR_BTNFACE),
                           wxSystemSettings::GetColour(wxSYS_COLOUR_BTNFACE));
  m_banner436->SetForegroundColour(
      wxSystemSettings::GetColour(wxSYS_COLOUR_BTNTEXT));

  boxSizer382->Add(m_banner436, 0, wxALL | wxEXPAND, WXC_FROM_DIP(5));

  flexGridSizer821 = new wxFlexGridSizer(0, 2, 0, 0);
  flexGridSizer821->SetFlexibleDirection(wxBOTH);
  flexGridSizer821->SetNonFlexibleGrowMode(wxFLEX_GROWMODE_SPECIFIED);
  flexGridSizer821->AddGrowableCol(1);

  boxSizer382->Add(flexGridSizer821, 0, wxALL | wxEXPAND, WXC_FROM_DIP(5));

  m_staticText832 = new wxStaticText(
      m_wizardPageWhatToLaunch, wxID_ANY, _("Name:"), wxDefaultPosition,
      wxDLG_UNIT(m_wizardPageWhatToLaunch, wxSize(-1, -1)), 0);

  flexGridSizer821->Add(m_staticText832, 0,
                        wxALL | wxALIGN_RIGHT | wxALIGN_CENTER_VERTICAL,
                        WXC_FROM_DIP(5));

  m_textCtrlName = new wxTextCtrl(
      m_wizardPageWhatToLaunch, wxID_ANY, wxT(""), wxDefaultPosition,
      wxDLG_UNIT(m_wizardPageWhatToLaunch, wxSize(350, -1)), 0);
  m_textCtrlName->SetFocus();
#if wxVERSION_NUMBER >= 3000
  m_textCtrlName->SetHint(wxT(""));
#endif

  flexGridSizer821->Add(m_textCtrlName, 0, wxALL | wxEXPAND, WXC_FROM_DIP(5));

  m_staticText2954 = new wxStaticText(
      m_wizardPageWhatToLaunch, wxID_ANY, _("Executable:"), wxDefaultPosition,
      wxDLG_UNIT(m_wizardPageWhatToLaunch, wxSize(-1, -1)), 0);

  flexGridSizer821->Add(m_staticText2954, 0,
                        wxALL | wxALIGN_RIGHT | wxALIGN_CENTER_VERTICAL,
                        WXC_FROM_DIP(5));

  wxArrayString m_comboBoxExecutableArr;
  m_comboBoxExecutable = new wxComboBox(
      m_wizardPageWhatToLaunch, wxID_ANY, wxT(""), wxDefaultPosition,
      wxDLG_UNIT(m_wizardPageWhatToLaunch, wxSize(-1, -1)),
      m_comboBoxExecutableArr, 0);
#if wxVERSION_NUMBER >= 3000
  m_comboBoxExecutable->SetHint(wxT(""));
#endif

  flexGridSizer821->Add(m_comboBoxExecutable, 0, wxALL | wxEXPAND,
                        WXC_FROM_DIP(5));

  m_staticText896 = new wxStaticText(
      m_wizardPageWhatToLaunch, wxID_ANY, _("Launch Args:"), wxDefaultPosition,
      wxDLG_UNIT(m_wizardPageWhatToLaunch, wxSize(-1, -1)), 0);

  flexGridSizer821->Add(m_staticText896, 0,
                        wxALL | wxALIGN_RIGHT | wxALIGN_CENTER_VERTICAL,
                        WXC_FROM_DIP(5));

  m_textCtrlLaunchArgs = new wxTextCtrl(
      m_wizardPageWhatToLaunch, wxID_ANY, wxT(""), wxDefaultPosition,
      wxDLG_UNIT(m_wizardPageWhatToLaunch, wxSize(-1, -1)), 0);
#if wxVERSION_NUMBER >= 3000
  m_textCtrlLaunchArgs->SetHint(_("e.g. --agent my-agent"));
#endif

  flexGridSizer821->Add(m_textCtrlLaunchArgs, 0, wxALL | wxEXPAND,
                        WXC_FROM_DIP(5));

  m_staticText2938 = new wxStaticText(
      m_wizardPageWhatToLaunch, wxID_ANY, _("Resume Args:"), wxDefaultPosition,
      wxDLG_UNIT(m_wizardPageWhatToLaunch, wxSize(-1, -1)), 0);

  flexGridSizer821->Add(m_staticText2938, 0,
                        wxALL | wxALIGN_RIGHT | wxALIGN_CENTER_VERTICAL,
                        WXC_FROM_DIP(5));

  wxBoxSizer *boxSizer3309 = new wxBoxSizer(wxHORIZONTAL);

  flexGridSizer821->Add(boxSizer3309, 0, wxEXPAND, WXC_FROM_DIP(5));

  m_textCtrlResumeArgs = new wxTextCtrl(
      m_wizardPageWhatToLaunch, wxID_ANY, wxT(""), wxDefaultPosition,
      wxDLG_UNIT(m_wizardPageWhatToLaunch, wxSize(-1, -1)), 0);
#if wxVERSION_NUMBER >= 3000
  m_textCtrlResumeArgs->SetHint(_("e.g. --resume"));
#endif

  boxSizer3309->Add(m_textCtrlResumeArgs, 1, wxALL | wxALIGN_CENTER_VERTICAL,
                    WXC_FROM_DIP(5));

  m_buttonResumeArgs = new wxButton(
      m_wizardPageWhatToLaunch, wxID_ANY, _("..."), wxDefaultPosition,
      wxDLG_UNIT(m_wizardPageWhatToLaunch, wxSize(-1, -1)), wxBU_EXACTFIT);
  m_buttonResumeArgs->SetToolTip(_("Suggest"));

  boxSizer3309->Add(m_buttonResumeArgs, 0, wxALL | wxALIGN_CENTER_VERTICAL,
                    WXC_FROM_DIP(5));

  m_staticText9914 = new wxStaticText(
      m_wizardPageWhatToLaunch, wxID_ANY, _("Image:"), wxDefaultPosition,
      wxDLG_UNIT(m_wizardPageWhatToLaunch, wxSize(-1, -1)), 0);

  flexGridSizer821->Add(m_staticText9914, 0,
                        wxALL | wxALIGN_RIGHT | wxALIGN_CENTER_VERTICAL,
                        WXC_FROM_DIP(5));

  wxBoxSizer *boxSizer15415 = new wxBoxSizer(wxHORIZONTAL);

  flexGridSizer821->Add(boxSizer15415, 1, wxEXPAND, WXC_FROM_DIP(5));

  m_textCtrlBitmap = new wxTextCtrl(
      m_wizardPageWhatToLaunch, wxID_ANY, wxT(""), wxDefaultPosition,
      wxDLG_UNIT(m_wizardPageWhatToLaunch, wxSize(-1, -1)), 0);
#if wxVERSION_NUMBER >= 3000
  m_textCtrlBitmap->SetHint(wxT(""));
#endif

  boxSizer15415->Add(m_textCtrlBitmap, 1, wxALL, WXC_FROM_DIP(5));

  m_button15517 = new wxButton(
      m_wizardPageWhatToLaunch, wxID_ANY, _("..."), wxDefaultPosition,
      wxDLG_UNIT(m_wizardPageWhatToLaunch, wxSize(-1, -1)), wxBU_EXACTFIT);

  boxSizer15415->Add(m_button15517, 0, wxALL | wxALIGN_CENTER_VERTICAL,
                     WXC_FROM_DIP(5));

  m_wizardPageAdvanced = new wxWizardPageSimple(this, NULL, NULL, wxNullBitmap);
  m_pages.push_back(m_wizardPageAdvanced);
  if (m_pages.size() > 1) {
    for (size_t i = 1; i < m_pages.size(); i++) {
      wxWizardPageSimple::Chain(m_pages.at(i - 1), m_pages.at(i));
    }
  }
  GetPageAreaSizer()->Add(m_pages.at(0));

  wxBoxSizer *boxSizer489 = new wxBoxSizer(wxHORIZONTAL);
  m_wizardPageAdvanced->SetSizer(boxSizer489);

  m_bannerAdvancedBimap = new wxBannerWindow(
      m_wizardPageAdvanced, wxID_ANY, wxLEFT, wxDefaultPosition,
      wxDLG_UNIT(m_wizardPageAdvanced, wxSize(-1, -1)), 0);
  m_bannerAdvancedBimap->SetBitmap(wxNullBitmap);
  m_bannerAdvancedBimap->SetText(wxT(""), wxT(""));

  boxSizer489->Add(m_bannerAdvancedBimap, 0, wxALL | wxEXPAND, WXC_FROM_DIP(5));

  wxBoxSizer *boxSizer384 = new wxBoxSizer(wxVERTICAL);

  boxSizer489->Add(boxSizer384, 1, wxALL | wxEXPAND, WXC_FROM_DIP(5));

  m_banner474 = new wxBannerWindow(
      m_wizardPageAdvanced, wxID_ANY, wxTOP, wxDefaultPosition,
      wxDLG_UNIT(m_wizardPageAdvanced, wxSize(-1, -1)), 0);
  m_banner474->SetBitmap(wxNullBitmap);
  m_banner474->SetText(_("Shell & Environment"),
                       _("Select which shell to use and define any extra "
                         "environment variables."));
  m_banner474->SetGradient(wxSystemSettings::GetColour(wxSYS_COLOUR_BTNFACE),
                           wxSystemSettings::GetColour(wxSYS_COLOUR_BTNFACE));
  m_banner474->SetForegroundColour(
      wxSystemSettings::GetColour(wxSYS_COLOUR_BTNTEXT));

  boxSizer384->Add(m_banner474, 0, wxALL | wxEXPAND, WXC_FROM_DIP(5));

  wxFlexGridSizer *flexGridSizer485 = new wxFlexGridSizer(0, 2, 0, 0);
  flexGridSizer485->SetFlexibleDirection(wxBOTH);
  flexGridSizer485->SetNonFlexibleGrowMode(wxFLEX_GROWMODE_SPECIFIED);
  flexGridSizer485->AddGrowableCol(1);

  boxSizer384->Add(flexGridSizer485, 0, wxALL | wxEXPAND, WXC_FROM_DIP(5));

  m_staticTextLoginShell = new wxStaticText(
      m_wizardPageAdvanced, wxID_ANY, _("Login Shell:"), wxDefaultPosition,
      wxDLG_UNIT(m_wizardPageAdvanced, wxSize(-1, -1)), 0);

  flexGridSizer485->Add(m_staticTextLoginShell, 0,
                        wxALL | wxALIGN_RIGHT | wxALIGN_CENTER_VERTICAL,
                        WXC_FROM_DIP(5));

  wxArrayString m_choiceShellArr;
  m_choiceShell = new wxChoice(
      m_wizardPageAdvanced, wxID_ANY, wxDefaultPosition,
      wxDLG_UNIT(m_wizardPageAdvanced, wxSize(-1, -1)), m_choiceShellArr, 0);

  flexGridSizer485->Add(m_choiceShell, 0, wxALL | wxEXPAND, WXC_FROM_DIP(5));

  wxBoxSizer *boxSizer9536 = new wxBoxSizer(wxHORIZONTAL);

  boxSizer384->Add(boxSizer9536, 1, wxALL | wxEXPAND, WXC_FROM_DIP(5));

  m_dvListCtrlEnv =
      new wxDataViewListCtrl(m_wizardPageAdvanced, wxID_ANY, wxDefaultPosition,
                             wxDLG_UNIT(m_wizardPageAdvanced, wxSize(-1, 100)),
                             wxDV_ROW_LINES | wxDV_SINGLE);

  boxSizer9536->Add(m_dvListCtrlEnv, 1, wxALL | wxEXPAND, WXC_FROM_DIP(5));

  m_dvListCtrlEnv->AppendTextColumn(_("Name"), wxDATAVIEW_CELL_INERT,
                                    WXC_FROM_DIP(-2), wxALIGN_LEFT, 0);
  m_dvListCtrlEnv->AppendTextColumn(_("Value"), wxDATAVIEW_CELL_INERT,
                                    WXC_FROM_DIP(-2), wxALIGN_LEFT, 0);
  wxBoxSizer *boxSizer9640 = new wxBoxSizer(wxVERTICAL);

  boxSizer9536->Add(boxSizer9640, 0, wxEXPAND, WXC_FROM_DIP(5));

  m_buttonNewEnv41 =
      new wxButton(m_wizardPageAdvanced, wxID_ANY, _("New"), wxDefaultPosition,
                   wxDLG_UNIT(m_wizardPageAdvanced, wxSize(-1, -1)), 0);

  boxSizer9640->Add(m_buttonNewEnv41, 0, wxALL | wxEXPAND, WXC_FROM_DIP(5));

  m_buttonDeleteEnv42 = new wxButton(
      m_wizardPageAdvanced, wxID_ANY, _("Delete"), wxDefaultPosition,
      wxDLG_UNIT(m_wizardPageAdvanced, wxSize(-1, -1)), 0);

  boxSizer9640->Add(m_buttonDeleteEnv42, 0, wxALL | wxEXPAND, WXC_FROM_DIP(5));

  SetName(wxT("NewAgentWizardBase"));
  SetSize(wxDLG_UNIT(this, wxSize(-1, -1)));
  if (GetSizer()) {
    GetSizer()->Fit(this);
  }
  if (GetParent()) {
    CentreOnParent(wxBOTH);
  } else {
    CentreOnScreen(wxBOTH);
  }
  if (!wxPersistenceManager::Get().Find(this)) {
    wxPersistenceManager::Get().RegisterAndRestore(this);
  } else {
    wxPersistenceManager::Get().Restore(this);
  }
  // Connect events
  m_staticText28930->Bind(wxEVT_UPDATE_UI,
                          &NewAgentWizardBase::OnEnableRemoteUI, this);
  m_textCtrlHost->Bind(wxEVT_UPDATE_UI, &NewAgentWizardBase::OnEnableRemoteUI,
                       this);
  m_button29233->Bind(wxEVT_UPDATE_UI, &NewAgentWizardBase::OnEnableRemoteUI,
                      this);
  m_button29233->Bind(wxEVT_COMMAND_BUTTON_CLICKED,
                      &NewAgentWizardBase::OnBrowseHosts, this);
  m_staticText32934->Bind(wxEVT_UPDATE_UI,
                          &NewAgentWizardBase::OnEnableRemoteUI, this);
  m_textCtrlUser->Bind(wxEVT_UPDATE_UI, &NewAgentWizardBase::OnEnableRemoteUI,
                       this);
  m_buttonResumeArgs->Bind(wxEVT_COMMAND_BUTTON_CLICKED,
                           &NewAgentWizardBase::OnBrowseResumeArgs, this);
  m_button15517->Bind(wxEVT_COMMAND_BUTTON_CLICKED,
                      &NewAgentWizardBase::OnBrowseBitmap, this);
  m_buttonNewEnv41->Bind(wxEVT_COMMAND_BUTTON_CLICKED,
                         &NewAgentWizardBase::OnNewEnv, this);
  m_buttonDeleteEnv42->Bind(wxEVT_COMMAND_BUTTON_CLICKED,
                            &NewAgentWizardBase::OnDeleteEnv, this);
  m_buttonDeleteEnv42->Bind(wxEVT_UPDATE_UI, &NewAgentWizardBase::OnDeleteEnvUI,
                            this);
}

NewAgentWizardBase::~NewAgentWizardBase() {
  m_staticText28930->Unbind(wxEVT_UPDATE_UI,
                            &NewAgentWizardBase::OnEnableRemoteUI, this);
  m_textCtrlHost->Unbind(wxEVT_UPDATE_UI, &NewAgentWizardBase::OnEnableRemoteUI,
                         this);
  m_button29233->Unbind(wxEVT_UPDATE_UI, &NewAgentWizardBase::OnEnableRemoteUI,
                        this);
  m_button29233->Unbind(wxEVT_COMMAND_BUTTON_CLICKED,
                        &NewAgentWizardBase::OnBrowseHosts, this);
  m_staticText32934->Unbind(wxEVT_UPDATE_UI,
                            &NewAgentWizardBase::OnEnableRemoteUI, this);
  m_textCtrlUser->Unbind(wxEVT_UPDATE_UI, &NewAgentWizardBase::OnEnableRemoteUI,
                         this);
  m_buttonResumeArgs->Unbind(wxEVT_COMMAND_BUTTON_CLICKED,
                             &NewAgentWizardBase::OnBrowseResumeArgs, this);
  m_button15517->Unbind(wxEVT_COMMAND_BUTTON_CLICKED,
                        &NewAgentWizardBase::OnBrowseBitmap, this);
  m_buttonNewEnv41->Unbind(wxEVT_COMMAND_BUTTON_CLICKED,
                           &NewAgentWizardBase::OnNewEnv, this);
  m_buttonDeleteEnv42->Unbind(wxEVT_COMMAND_BUTTON_CLICKED,
                              &NewAgentWizardBase::OnDeleteEnv, this);
  m_buttonDeleteEnv42->Unbind(wxEVT_UPDATE_UI,
                              &NewAgentWizardBase::OnDeleteEnvUI, this);
}
