//////////////////////////////////////////////////////////////////////
// This file was auto-generated by CodeLite's wxCrafter Plugin
// wxCrafter project file: UI.wxcp
// Do not modify this file by hand!
//////////////////////////////////////////////////////////////////////

#ifndef _SRC_APP_UI_BASE_CLASSES_HPP
#define _SRC_APP_UI_BASE_CLASSES_HPP

// clang-format off
#include <wx/settings.h>
#include <wx/xrc/xmlres.h>
#include <wx/xrc/xh_bmp.h>
#include <wx/panel.h>
#include <wx/artprov.h>
#include <wx/sizer.h>
#include <wx/splitter.h>
#include <wx/dataview.h>
#include <wx/simplebook.h>
#include <wx/dialog.h>
#include <wx/iconbndl.h>
#include <wx/statbox.h>
#include <wx/stattext.h>
#include <wx/choice.h>
#include <wx/arrstr.h>
#include <wx/textctrl.h>
#include <wx/combobox.h>
#include <wx/button.h>
#include <wx/checkbox.h>
#include <wx/toolbar.h>
#include <wx/stc/stc.h>
#include <wx/notebook.h>
#include <wx/imaglist.h>
#include <wx/statbmp.h>
#include <wx/pen.h>
#include <wx/aui/auibar.h>
#include <map>
#include <wx/menu.h>
#include <wx/fontpicker.h>
#include <wx/spinctrl.h>
#include <wx/wizard.h>
#include <vector>
#include <wx/bannerwindow.h>
#if wxVERSION_NUMBER >= 2900
#include <wx/persist.h>
#include <wx/persist/toplevel.h>
#include <wx/persist/bookctrl.h>
#include <wx/persist/treebook.h>
#endif

#ifdef WXC_FROM_DIP
#undef WXC_FROM_DIP
#endif
#if wxVERSION_NUMBER >= 3100
#define WXC_FROM_DIP(x) wxWindow::FromDIP(x, NULL)
#else
#define WXC_FROM_DIP(x) x
#endif

// clang-format on

class SessionBasePage : public wxPanel {
protected:
protected:
public:
  SessionBasePage(wxWindow *parent, wxWindowID id = wxID_ANY,
                  const wxPoint &pos = wxDefaultPosition,
                  const wxSize &size = wxSize(500, 300),
                  long style = wxTAB_TRAVERSAL);
  virtual ~SessionBasePage();
};

class MainViewBase : public wxPanel {
protected:
  wxSplitterWindow *m_splitterMain;
  wxPanel *m_splitterPageLeft;
  wxBoxSizer *m_leftPaneMainSizer;
  wxDataViewListCtrl *m_dvListCtrlGroups;
  wxPanel *m_splitterPageRight;
  wxSimplebook *m_sessionsBook;

protected:
  virtual void OnSelectionChanged(wxDataViewEvent &event) { event.Skip(); }
  virtual void OnContextMenu(wxDataViewEvent &event) { event.Skip(); }

public:
  wxDataViewListCtrl *GetDvListCtrlGroups() { return m_dvListCtrlGroups; }
  wxPanel *GetSplitterPageLeft() { return m_splitterPageLeft; }
  wxSimplebook *GetSessionsBook() { return m_sessionsBook; }
  wxPanel *GetSplitterPageRight() { return m_splitterPageRight; }
  wxSplitterWindow *GetSplitterMain() { return m_splitterMain; }
  MainViewBase(wxWindow *parent, wxWindowID id = wxID_ANY,
               const wxPoint &pos = wxDefaultPosition,
               const wxSize &size = wxSize(-1, -1),
               long style = wxTAB_TRAVERSAL);
  virtual ~MainViewBase();
};

class StartAgentDialogBase : public wxDialog {
protected:
  wxStaticText *m_staticText22;
  wxChoice *m_choiceClients;
  wxStaticText *m_staticTextName;
  wxTextCtrl *m_textCtrlName;
  wxStaticText *m_staticTextErrorMessage;
  wxStaticText *m_staticText343;
  wxComboBox *m_comboBoxGroup;
  wxStaticText *m_staticText24;
  wxComboBox *m_comboBoxWorkingDir;
  wxButton *m_buttonBrowseWD;
  wxCheckBox *m_checkBoxInnderFolder;
  wxCheckBox *m_checkBoxResume;
  wxStdDialogButtonSizer *m_stdBtnSizer17;
  wxButton *m_buttonOk;
  wxButton *m_buttonCancel;

protected:
  virtual void OnNameUpdated(wxCommandEvent &event) { event.Skip(); }
  virtual void OnBrowseWdUI(wxUpdateUIEvent &event) { event.Skip(); }
  virtual void OnBrowseWD(wxCommandEvent &event) { event.Skip(); }
  virtual void OnInnerFolder(wxCommandEvent &event) { event.Skip(); }
  virtual void OnOkUI(wxUpdateUIEvent &event) { event.Skip(); }

public:
  wxStaticText *GetStaticText22() { return m_staticText22; }
  wxChoice *GetChoiceClients() { return m_choiceClients; }
  wxStaticText *GetStaticTextName() { return m_staticTextName; }
  wxTextCtrl *GetTextCtrlName() { return m_textCtrlName; }
  wxStaticText *GetStaticTextErrorMessage() { return m_staticTextErrorMessage; }
  wxStaticText *GetStaticText343() { return m_staticText343; }
  wxComboBox *GetComboBoxGroup() { return m_comboBoxGroup; }
  wxStaticText *GetStaticText24() { return m_staticText24; }
  wxComboBox *GetComboBoxWorkingDir() { return m_comboBoxWorkingDir; }
  wxButton *GetButtonBrowseWD() { return m_buttonBrowseWD; }
  wxCheckBox *GetCheckBoxInnderFolder() { return m_checkBoxInnderFolder; }
  wxCheckBox *GetCheckBoxResume() { return m_checkBoxResume; }
  StartAgentDialogBase(wxWindow *parent, wxWindowID id = wxID_ANY,
                       const wxString &title = _("Start Agent"),
                       const wxPoint &pos = wxDefaultPosition,
                       const wxSize &size = wxSize(-1, -1),
                       long style = wxDEFAULT_DIALOG_STYLE);
  virtual ~StartAgentDialogBase();
};

class EditFileDlgBase : public wxDialog {
protected:
  wxToolBar *m_toolbar;
  wxStyledTextCtrl *m_stcEditor;

protected:
public:
  wxToolBar *GetToolbar() { return m_toolbar; }
  wxStyledTextCtrl *GetStcEditor() { return m_stcEditor; }
  EditFileDlgBase(wxWindow *parent, wxWindowID id = wxID_ANY,
                  const wxString &title = _("Edit File"),
                  const wxPoint &pos = wxDefaultPosition,
                  const wxSize &size = wxSize(500, 300),
                  long style = wxDEFAULT_DIALOG_STYLE | wxRESIZE_BORDER);
  virtual ~EditFileDlgBase();
};

class EditHostsBase : public wxDialog {
protected:
  wxPanel *m_panel52;
  wxDataViewListCtrl *m_dvListCtrlHosts;
  wxButton *m_buttonNew;
  wxButton *m_buttonDelete;
  wxStdDialogButtonSizer *m_stdBtnSizer49;
  wxButton *m_button50;
  wxButton *m_button51;

protected:
  virtual void OnHostActivated(wxDataViewEvent &event) { event.Skip(); }
  virtual void OnHostSelected(wxDataViewEvent &event) { event.Skip(); }
  virtual void OnNew(wxCommandEvent &event) { event.Skip(); }
  virtual void OnDelete(wxCommandEvent &event) { event.Skip(); }
  virtual void OnDeleteUI(wxUpdateUIEvent &event) { event.Skip(); }

public:
  wxDataViewListCtrl *GetDvListCtrlHosts() { return m_dvListCtrlHosts; }
  wxButton *GetButtonNew() { return m_buttonNew; }
  wxButton *GetButtonDelete() { return m_buttonDelete; }
  wxPanel *GetPanel52() { return m_panel52; }
  EditHostsBase(wxWindow *parent, wxWindowID id = wxID_ANY,
                const wxString &title = _("Edit Hosts"),
                const wxPoint &pos = wxDefaultPosition,
                const wxSize &size = wxSize(-1, -1),
                long style = wxDEFAULT_DIALOG_STYLE | wxRESIZE_BORDER);
  virtual ~EditHostsBase();
};

class EditAgentDlgBase : public wxDialog {
protected:
  wxPanel *m_panel87;
  wxFlexGridSizer *flexGridSizer82;
  wxStaticText *m_staticText83;
  wxTextCtrl *m_textCtrlName;
  wxStaticText *m_staticText295;
  wxComboBox *m_comboBoxExecutable;
  wxStaticText *m_staticText89;
  wxTextCtrl *m_textCtrlLaunchArgs;
  wxStaticText *m_staticText293;
  wxTextCtrl *m_textCtrlResumeArgs;
  wxButton *m_button331;
  wxStaticText *m_staticText372;
  wxChoice *m_choiceShell;
  wxStaticText *m_staticText99;
  wxTextCtrl *m_textCtrlBitmap;
  wxButton *m_button155;
  wxStaticText *m_staticText289;
  wxTextCtrl *m_textCtrlHost;
  wxButton *m_button292;
  wxStaticText *m_staticText329;
  wxTextCtrl *m_textCtrlUser;
  wxDataViewListCtrl *m_dvListCtrlEnv;
  wxButton *m_buttonNewEnv;
  wxButton *m_buttonDeleteEnv;
  wxStdDialogButtonSizer *m_stdBtnSizer75;
  wxButton *m_buttonOk;
  wxButton *m_buttonCancel;

protected:
  virtual void OnSuggestResumeArgs(wxCommandEvent &event) { event.Skip(); }
  virtual void OnBrowseBitmap(wxCommandEvent &event) { event.Skip(); }
  virtual void OnRemoteHost(wxCommandEvent &event) { event.Skip(); }
  virtual void OnEnvActivated(wxDataViewEvent &event) { event.Skip(); }
  virtual void OnNewEnv(wxCommandEvent &event) { event.Skip(); }
  virtual void OnDeleteEnv(wxCommandEvent &event) { event.Skip(); }
  virtual void OnDeleteEnvUI(wxUpdateUIEvent &event) { event.Skip(); }
  virtual void OnOkUI(wxUpdateUIEvent &event) { event.Skip(); }
  virtual void OnOk(wxCommandEvent &event) { event.Skip(); }

public:
  wxStaticText *GetStaticText83() { return m_staticText83; }
  wxTextCtrl *GetTextCtrlName() { return m_textCtrlName; }
  wxStaticText *GetStaticText295() { return m_staticText295; }
  wxComboBox *GetComboBoxExecutable() { return m_comboBoxExecutable; }
  wxStaticText *GetStaticText89() { return m_staticText89; }
  wxTextCtrl *GetTextCtrlLaunchArgs() { return m_textCtrlLaunchArgs; }
  wxStaticText *GetStaticText293() { return m_staticText293; }
  wxTextCtrl *GetTextCtrlResumeArgs() { return m_textCtrlResumeArgs; }
  wxButton *GetButton331() { return m_button331; }
  wxStaticText *GetStaticText372() { return m_staticText372; }
  wxChoice *GetChoiceShell() { return m_choiceShell; }
  wxStaticText *GetStaticText99() { return m_staticText99; }
  wxTextCtrl *GetTextCtrlBitmap() { return m_textCtrlBitmap; }
  wxButton *GetButton155() { return m_button155; }
  wxStaticText *GetStaticText289() { return m_staticText289; }
  wxTextCtrl *GetTextCtrlHost() { return m_textCtrlHost; }
  wxButton *GetButton292() { return m_button292; }
  wxStaticText *GetStaticText329() { return m_staticText329; }
  wxTextCtrl *GetTextCtrlUser() { return m_textCtrlUser; }
  wxDataViewListCtrl *GetDvListCtrlEnv() { return m_dvListCtrlEnv; }
  wxButton *GetButtonNewEnv() { return m_buttonNewEnv; }
  wxButton *GetButtonDeleteEnv() { return m_buttonDeleteEnv; }
  wxPanel *GetPanel87() { return m_panel87; }
  EditAgentDlgBase(wxWindow *parent, wxWindowID id = wxID_ANY,
                   const wxString &title = _("Edit / New Agent"),
                   const wxPoint &pos = wxDefaultPosition,
                   const wxSize &size = wxSize(-1, -1),
                   long style = wxDEFAULT_DIALOG_STYLE | wxRESIZE_BORDER);
  virtual ~EditAgentDlgBase();
};

class EditAgentsDlgBase : public wxDialog {
protected:
  wxPanel *m_panel106;
  wxDataViewListCtrl *m_dvListCtrlAgents;
  wxButton *m_buttonNew;
  wxButton *m_buttonEdit;
  wxButton *m_buttonDelete;
  wxStdDialogButtonSizer *m_stdBtnSizer103;
  wxButton *m_buttonOk;
  wxButton *m_buttonCancel;

protected:
  virtual void OnItemActivated(wxDataViewEvent &event) { event.Skip(); }
  virtual void OnNewAgent(wxCommandEvent &event) { event.Skip(); }
  virtual void OnEditAgent(wxCommandEvent &event) { event.Skip(); }
  virtual void OnEditAgentUI(wxUpdateUIEvent &event) { event.Skip(); }
  virtual void OnDelete(wxCommandEvent &event) { event.Skip(); }
  virtual void OnOK(wxCommandEvent &event) { event.Skip(); }

public:
  wxDataViewListCtrl *GetDvListCtrlAgents() { return m_dvListCtrlAgents; }
  wxButton *GetButtonNew() { return m_buttonNew; }
  wxButton *GetButtonEdit() { return m_buttonEdit; }
  wxButton *GetButtonDelete() { return m_buttonDelete; }
  wxPanel *GetPanel106() { return m_panel106; }
  EditAgentsDlgBase(wxWindow *parent, wxWindowID id = wxID_ANY,
                    const wxString &title = _("Manage Agents"),
                    const wxPoint &pos = wxDefaultPosition,
                    const wxSize &size = wxSize(-1, -1),
                    long style = wxDEFAULT_DIALOG_STYLE | wxRESIZE_BORDER);
  virtual ~EditAgentsDlgBase();
};

class AboutDialogBase : public wxDialog {
protected:
  wxPanel *m_panel123;
  wxNotebook *m_notebook125;
  wxPanel *m_panel126;
  wxStaticText *m_staticText129;
  wxTextCtrl *m_textCtrlName;
  wxStaticText *m_staticText132;
  wxTextCtrl *m_textCtrlVersion;
  wxStaticText *m_staticText134;
  wxTextCtrl *m_textCtrlAuthor;
  wxStaticText *m_staticText136;
  wxTextCtrl *m_textCtrlDescription;
  wxStaticBitmap *m_staticBitmapIcon;
  wxPanel *m_panel127;
  wxStyledTextCtrl *m_stcLicense;
  wxStdDialogButtonSizer *m_stdBtnSizer120;
  wxButton *m_button121;

protected:
public:
  wxStaticText *GetStaticText129() { return m_staticText129; }
  wxTextCtrl *GetTextCtrlName() { return m_textCtrlName; }
  wxStaticText *GetStaticText132() { return m_staticText132; }
  wxTextCtrl *GetTextCtrlVersion() { return m_textCtrlVersion; }
  wxStaticText *GetStaticText134() { return m_staticText134; }
  wxTextCtrl *GetTextCtrlAuthor() { return m_textCtrlAuthor; }
  wxStaticText *GetStaticText136() { return m_staticText136; }
  wxTextCtrl *GetTextCtrlDescription() { return m_textCtrlDescription; }
  wxStaticBitmap *GetStaticBitmapIcon() { return m_staticBitmapIcon; }
  wxPanel *GetPanel126() { return m_panel126; }
  wxStyledTextCtrl *GetStcLicense() { return m_stcLicense; }
  wxPanel *GetPanel127() { return m_panel127; }
  wxNotebook *GetNotebook125() { return m_notebook125; }
  wxPanel *GetPanel123() { return m_panel123; }
  AboutDialogBase(wxWindow *parent, wxWindowID id = wxID_ANY,
                  const wxString &title = _("About Kennel"),
                  const wxPoint &pos = wxDefaultPosition,
                  const wxSize &size = wxSize(-1, -1),
                  long style = wxDEFAULT_DIALOG_STYLE);
  virtual ~AboutDialogBase();
};

class FileBrowserDlgBase : public wxDialog {
protected:
  wxAuiToolBar *m_auibar;
  wxPanel *m_panel320;
  wxDataViewListCtrl *m_dvListCtrl;
  wxPanel *m_panelPreview;
  wxStaticBitmap *m_staticBitmapPreview;
  wxTextCtrl *m_textCtrlCurrnentDir;
  wxButton *m_button323;

protected:
  virtual void OnActivated(wxDataViewEvent &event) { event.Skip(); }
  virtual void OnKeyDown(wxKeyEvent &event) { event.Skip(); }
  virtual void OnSelectionChanged(wxDataViewEvent &event) { event.Skip(); }
  virtual void OnSelect(wxCommandEvent &event) { event.Skip(); }
  virtual void OnSelectUI(wxUpdateUIEvent &event) { event.Skip(); }

public:
  wxAuiToolBar *GetAuibar() { return m_auibar; }
  wxDataViewListCtrl *GetDvListCtrl() { return m_dvListCtrl; }
  wxStaticBitmap *GetStaticBitmapPreview() { return m_staticBitmapPreview; }
  wxPanel *GetPanelPreview() { return m_panelPreview; }
  wxTextCtrl *GetTextCtrlCurrnentDir() { return m_textCtrlCurrnentDir; }
  wxButton *GetButton323() { return m_button323; }
  wxPanel *GetPanel320() { return m_panel320; }
  FileBrowserDlgBase(wxWindow *parent, wxWindowID id = wxID_ANY,
                     const wxString &title = _("File Browser"),
                     const wxPoint &pos = wxDefaultPosition,
                     const wxSize &size = wxSize(-1, -1),
                     long style = wxDEFAULT_DIALOG_STYLE | wxRESIZE_BORDER);
  virtual ~FileBrowserDlgBase();
};

class NewEnvVarDlgBase : public wxDialog {
protected:
  wxStaticText *m_staticText312;
  wxTextCtrl *m_textCtrlName;
  wxStaticText *m_staticText314;
  wxTextCtrl *m_textCtrlValue;
  wxStdDialogButtonSizer *m_stdBtnSizer308;
  wxButton *m_buttonOK;
  wxButton *m_buttonCancel;

protected:
  virtual void OnOkUI(wxUpdateUIEvent &event) { event.Skip(); }

public:
  wxStaticText *GetStaticText312() { return m_staticText312; }
  wxTextCtrl *GetTextCtrlName() { return m_textCtrlName; }
  wxStaticText *GetStaticText314() { return m_staticText314; }
  wxTextCtrl *GetTextCtrlValue() { return m_textCtrlValue; }
  NewEnvVarDlgBase(wxWindow *parent, wxWindowID id = wxID_ANY,
                   const wxString &title = _("New / Edit Environment Variable"),
                   const wxPoint &pos = wxDefaultPosition,
                   const wxSize &size = wxSize(-1, -1),
                   long style = wxDEFAULT_DIALOG_STYLE);
  virtual ~NewEnvVarDlgBase();
};

class SettingsDlgBase : public wxDialog {
protected:
  wxPanel *m_panel350;
  wxNotebook *m_notebook352;
  wxPanel *m_panel353;
  wxStaticText *m_staticText355;
  wxChoice *m_choiceTheme;
  wxStaticText *m_staticText357;
  wxFontPickerCtrl *m_fontPicker;
  wxPanel *m_panel361;
  wxStaticText *m_staticText365;
  wxChoice *m_choiceShell;
  wxStaticText *m_staticText498;
  wxTextCtrl *m_textCtrlShellWorkingDir;
  wxButton *m_button508;
  wxStaticText *m_staticText504;
  wxSpinCtrl *m_spinCtrlScrollBackLines;
  wxCheckBox *m_checkBoxBlockCaret;
  wxCheckBox *m_checkBoxOptimizeDrawings;
  wxCheckBox *m_checkBoxForNewVersionOnStartup;
  wxStdDialogButtonSizer *m_stdBtnSizer347;
  wxButton *m_buttonOk;
  wxButton *m_buttonCancel;

protected:
  virtual void OnChoiceTheme(wxCommandEvent &event) { event.Skip(); }
  virtual void OnFontSelected(wxFontPickerEvent &event) { event.Skip(); }
  virtual void OnBrowseForShellWorkingDir(wxCommandEvent &event) {
    event.Skip();
  }

public:
  wxStaticText *GetStaticText355() { return m_staticText355; }
  wxChoice *GetChoiceTheme() { return m_choiceTheme; }
  wxStaticText *GetStaticText357() { return m_staticText357; }
  wxFontPickerCtrl *GetFontPicker() { return m_fontPicker; }
  wxPanel *GetPanel353() { return m_panel353; }
  wxStaticText *GetStaticText365() { return m_staticText365; }
  wxChoice *GetChoiceShell() { return m_choiceShell; }
  wxStaticText *GetStaticText498() { return m_staticText498; }
  wxTextCtrl *GetTextCtrlShellWorkingDir() { return m_textCtrlShellWorkingDir; }
  wxButton *GetButton508() { return m_button508; }
  wxStaticText *GetStaticText504() { return m_staticText504; }
  wxSpinCtrl *GetSpinCtrlScrollBackLines() { return m_spinCtrlScrollBackLines; }
  wxCheckBox *GetCheckBoxBlockCaret() { return m_checkBoxBlockCaret; }
  wxCheckBox *GetCheckBoxOptimizeDrawings() {
    return m_checkBoxOptimizeDrawings;
  }
  wxCheckBox *GetCheckBoxForNewVersionOnStartup() {
    return m_checkBoxForNewVersionOnStartup;
  }
  wxPanel *GetPanel361() { return m_panel361; }
  wxNotebook *GetNotebook352() { return m_notebook352; }
  wxPanel *GetPanel350() { return m_panel350; }
  SettingsDlgBase(wxWindow *parent, wxWindowID id = wxID_ANY,
                  const wxString &title = _("Settings"),
                  const wxPoint &pos = wxDefaultPosition,
                  const wxSize &size = wxSize(-1, -1),
                  long style = wxDEFAULT_DIALOG_STYLE);
  virtual ~SettingsDlgBase();
};

class NewAgentWizardBase : public wxWizard {
protected:
  std::vector<wxWizardPageSimple *> m_pages;

  wxWizardPageSimple *m_wizardPageLocalOrRemote;
  wxBannerWindow *m_bannerLocalOrRemoteBitmap;
  wxBannerWindow *m_banner473;
  wxCheckBox *m_checkBoxLocalHost;
  wxStaticText *m_staticText28930;
  wxTextCtrl *m_textCtrlHost;
  wxButton *m_button29233;
  wxStaticText *m_staticText32934;
  wxTextCtrl *m_textCtrlUser;
  wxWizardPageSimple *m_wizardPageWhatToLaunch;
  wxBannerWindow *m_bannerWhatToLaunchBitmap;
  wxBannerWindow *m_banner436;
  wxFlexGridSizer *flexGridSizer821;
  wxStaticText *m_staticText832;
  wxTextCtrl *m_textCtrlName;
  wxStaticText *m_staticText2954;
  wxComboBox *m_comboBoxExecutable;
  wxStaticText *m_staticText896;
  wxTextCtrl *m_textCtrlLaunchArgs;
  wxStaticText *m_staticText2938;
  wxTextCtrl *m_textCtrlResumeArgs;
  wxButton *m_buttonResumeArgs;
  wxStaticText *m_staticText9914;
  wxTextCtrl *m_textCtrlBitmap;
  wxButton *m_button15517;
  wxWizardPageSimple *m_wizardPageAdvanced;
  wxBannerWindow *m_bannerAdvancedBimap;
  wxBannerWindow *m_banner474;
  wxStaticText *m_staticTextLoginShell;
  wxChoice *m_choiceShell;
  wxDataViewListCtrl *m_dvListCtrlEnv;
  wxButton *m_buttonNewEnv41;
  wxButton *m_buttonDeleteEnv42;

protected:
  virtual void OnEnableRemoteUI(wxUpdateUIEvent &event) { event.Skip(); }
  virtual void OnBrowseHosts(wxCommandEvent &event) { event.Skip(); }
  virtual void OnBrowseResumeArgs(wxCommandEvent &event) { event.Skip(); }
  virtual void OnBrowseBitmap(wxCommandEvent &event) { event.Skip(); }
  virtual void OnNewEnv(wxCommandEvent &event) { event.Skip(); }
  virtual void OnDeleteEnv(wxCommandEvent &event) { event.Skip(); }
  virtual void OnDeleteEnvUI(wxUpdateUIEvent &event) { event.Skip(); }

public:
  wxBannerWindow *GetBannerLocalOrRemoteBitmap() {
    return m_bannerLocalOrRemoteBitmap;
  }
  wxBannerWindow *GetBanner473() { return m_banner473; }
  wxCheckBox *GetCheckBoxLocalHost() { return m_checkBoxLocalHost; }
  wxStaticText *GetStaticText28930() { return m_staticText28930; }
  wxTextCtrl *GetTextCtrlHost() { return m_textCtrlHost; }
  wxButton *GetButton29233() { return m_button29233; }
  wxStaticText *GetStaticText32934() { return m_staticText32934; }
  wxTextCtrl *GetTextCtrlUser() { return m_textCtrlUser; }
  wxWizardPageSimple *GetWizardPageLocalOrRemote() {
    return m_wizardPageLocalOrRemote;
  }
  wxBannerWindow *GetBannerWhatToLaunchBitmap() {
    return m_bannerWhatToLaunchBitmap;
  }
  wxBannerWindow *GetBanner436() { return m_banner436; }
  wxStaticText *GetStaticText832() { return m_staticText832; }
  wxTextCtrl *GetTextCtrlName() { return m_textCtrlName; }
  wxStaticText *GetStaticText2954() { return m_staticText2954; }
  wxComboBox *GetComboBoxExecutable() { return m_comboBoxExecutable; }
  wxStaticText *GetStaticText896() { return m_staticText896; }
  wxTextCtrl *GetTextCtrlLaunchArgs() { return m_textCtrlLaunchArgs; }
  wxStaticText *GetStaticText2938() { return m_staticText2938; }
  wxTextCtrl *GetTextCtrlResumeArgs() { return m_textCtrlResumeArgs; }
  wxButton *GetButtonResumeArgs() { return m_buttonResumeArgs; }
  wxStaticText *GetStaticText9914() { return m_staticText9914; }
  wxTextCtrl *GetTextCtrlBitmap() { return m_textCtrlBitmap; }
  wxButton *GetButton15517() { return m_button15517; }
  wxWizardPageSimple *GetWizardPageWhatToLaunch() {
    return m_wizardPageWhatToLaunch;
  }
  wxBannerWindow *GetBannerAdvancedBimap() { return m_bannerAdvancedBimap; }
  wxBannerWindow *GetBanner474() { return m_banner474; }
  wxStaticText *GetStaticTextLoginShell() { return m_staticTextLoginShell; }
  wxChoice *GetChoiceShell() { return m_choiceShell; }
  wxDataViewListCtrl *GetDvListCtrlEnv() { return m_dvListCtrlEnv; }
  wxButton *GetButtonNewEnv41() { return m_buttonNewEnv41; }
  wxButton *GetButtonDeleteEnv42() { return m_buttonDeleteEnv42; }
  wxWizardPageSimple *GetWizardPageAdvanced() { return m_wizardPageAdvanced; }
  NewAgentWizardBase(wxWindow *parent, wxWindowID id = wxID_ANY,
                     const wxString &title = _("New Agent"),
                     const wxBitmap &bmp = wxNullBitmap,
                     const wxPoint &pos = wxDefaultPosition,
                     long style = wxDEFAULT_DIALOG_STYLE);
  wxWizardPageSimple *GetFirstPage() const {
    if (!m_pages.empty())
      return m_pages.at(0);
    return NULL;
  }
  virtual ~NewAgentWizardBase();
};

#endif
